### PR TITLE
Fix library verification when installing from git repo or zip file

### LINKED ISSUE #1306: Using --git-url fails to install library due to repository and header name mismatch
### Current behavior

`arduino-cli lib install --git-url https://github.com/ThingPulse/esp8266-oled-ssd1306`

When running the above command, I receive an error: `Error installing Git Library: library is not valid: missing header file "esp8266-oled-ssd1306.h"`

This particular library doesn't have a header file named that. What is interesting though is if I instead install the library by the name, then it installs exactly the same repository with no issues. Here is that command:

`arduino-cli lib install "ESP8266 and ESP32 Oled Driver for SSD1306 displays"`

I verified it was the exact same library by using `arduino-cli lib search`

### Expected behavior

When pulling using Git repositories, it should install the libraries the same way it does when specifying by name.

### Environment

- CLI version (output of `arduino-cli version`): 0.18.3
- OS and platform: Windows for testing, Linux for Travis CI

### Additional context

In previous versions of the CLI, we could specify the Git repository URLs with no problems. We specify quite a few libraries via the CLI in a Travis build. About half of them would need to be replaced with the name as found via `arduino-cli lib search` and there are a few that don't even show up in the library search, so the only way to retrieve them would be via the Git repository, which doesn't work because the name doesn't match.

### PR DESCRIPTION
**Pull request by silvanocerza**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Solves a bug.

- **What is the current behavior?**

When installing a library from a git repository or from a zip file the verification step strictly requires the library to contain an header file with the same name as the repository URL or as the root directory contained in the zip file.

This verification is too strict and doesn't respect the official [library specifications](https://arduino.github.io/arduino-cli/latest/library-specification/), so often valid libraries are rejected.

* **What is the new behavior?**

The verification step is now less strict and reflect the library specification closely.

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Nope.

* **Other information**:

Fix #1306.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

File: arduino/libraries/librariesmanager/install.go [hunk 1]
```diff
@@ -259,22 +260,49 @@ func parseGitURL(gitURL string) (string, error) {
...
-	if !dir.Join("src", libraryHeader).Exist() && !dir.Join(libraryHeader).Exist() {
-		return fmt.Errorf(tr(`library is not valid: missing header file "%s"`), libraryHeader)
+// validateLibrary verifies the dir contains a valid library, meaning it has either
+// library.properties file and an header in src/ or an header in its root folder.
+// Returns nil if dir contains a valid library, error on all other cases.
+func validateLibrary(dir *paths.Path) error {
+	if dir.NotExist() {
+		return fmt.Errorf(tr("directory doesn't exist: %s", dir))
+	}
+	re := regexp.MustCompile(`.hp*$`)
```
Comment (per1234) [inline arduino/libraries/librariesmanager/install.go:270]: I don't think this is appropriate. It will match on invalid extensions like `.hpppppp` and it will miss the other allowed header `.hh`:
https://github.com/arduino/arduino-cli/blob/71ce1a46009ab15296e9a877280505b62124fcaa/arduino/libraries/libraries.go#L236

There should be a single list of valid header extensions that is used everywhere. Something like this:
https://github.com/arduino/arduino-cli/blob/71ce1a46009ab15296e9a877280505b62124fcaa/arduino/globals/globals.go#L46-L51
Arduino Lint could make use of it too if it was exported. I had to duplicate the list in Arduino Lint since Arduino CLI didn't provide it via the API.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: arduino/libraries/librariesmanager/install.go (hunk 1 above)
Comment (silvanocerza) [reply arduino/libraries/librariesmanager/install.go:270]: Good point, didn't think about it. 🤔

File: arduino/libraries/librariesmanager/install.go [hunk 2]
```diff
@@ -259,22 +260,47 @@ func parseGitURL(gitURL string) (string, error) {
...
+	// Library format rev2
+	// https://arduino.github.io/arduino-cli/latest/library-specification/#15-library-format-rev-22
+	if headerFound, err := searchHeaderFile(dir.Join("src")); err != nil {
+		return err
+	} else if dir.Join("library.properties").Exist() && headerFound {
+		return nil
+	}
+
+	// Legacy library format
+	// https://arduino.github.io/arduino-cli/latest/library-specification/#old-library-format-pre-15
```
Comment (per1234) [inline arduino/libraries/librariesmanager/install.go:298]:
```suggestion
	// Recursive library layout
	// https://arduino.github.io/arduino-cli/latest/library-specification/#source-code
	if headerFound, err := searchHeaderFile(dir.Join("src")); err != nil {
		return err
	} else if dir.Join("library.properties").Exist() && headerFound {
		return nil
	}

	// Flat library layout
	// https://arduino.github.io/arduino-cli/latest/library-specification/#source-code
```
The exact meaning of the "1.5 format" has not been clearly defined, but from studying the source code I believe it is actually about the presence or absence of `library.properties` (legacy vs non-legacy). This code is about the recursive and flat library layouts. A non-legacy library can have either flat or recursive layout:


As for this "rev" stuff. I think it's essentially worthless (other than as evidence of how much we need a real specification versioning strategy) because there is no documentation of what is different between the "rev"s. All those revs are "1.5 format" and I believe they all supported the recursive layout.

File: arduino/libraries/librariesmanager/install_test.go [hunk 3]
```diff
@@ -62,3 +63,43 @@ func TestParseGitURL(t *testing.T) {
...
+	err = validateLibrary(emptyLib)
+	require.Errorf(t, err, "library not valid")
+
+	onlyPropertiesLib := tmpDir.Join("onlyPropertiesLib")
+	onlyPropertiesLib.Mkdir()
+	onlyPropertiesLib.Join("library.properties").WriteFile([]byte{})
+	err = validateLibrary(onlyPropertiesLib)
+	require.Errorf(t, err, "library not valid")
+
+	onlyHeaderLib := tmpDir.Join("onlyHeaderLib")
```
Comment (per1234) [inline arduino/libraries/librariesmanager/install_test.go:85]:
```suggestion
	onlyHeaderLib := tmpDir.Join("missingPropertiesLib")
```
I think this is a better description of what the library is intended to demonstrate (since an "only header" library can be valid if it has flat layout).

**Review by per1234 — CHANGES_REQUESTED** [review]

**Review by per1234 — APPROVED** [review]
Thanks Silvano!
