### PR TITLE
fix: consistent boards list ordering

### LINKED ISSUE #1909: Please make the output of the `board listall --format json` deterministic
### Describe the request

During the review of arduino/arduino-ide#1520, I noticed that the output of `board listall --format json` is not always the same. It's not a big deal, but it works fine with the non `json` output. It would be great to have the same result when I execute the same command twice. This also affects the gRPC API.

_Update:_
For completeness, the order of the boards inside a platform matches the `boards.txt` order, but the platforms' order seems "random".

### Describe the current behavior

I am using a CLI from c8ff0425:

```
% ./arduino-cli version                
arduino-cli  Version: git-snapshot Commit: c8ff0425 Date: 2022-10-06T06:38:53Z
```

I have the following platforms installed:
```
% ./arduino-cli core list              
ID                Installed Latest Name                          
arduino:mbed_nano 3.2.0     3.3.0  Arduino Mbed OS Nano Boards   
arduino:nrf52     1.0.2     1.0.2  Arduino nRF52 Boards          
littleBits:avr    1.0.0     1.0.0  littleBits Arduino AVR Modules
```

When I run `board listall` **without** the `--format json` flags, I always get the same result:
```
% ./arduino-cli board listall
Board Name                              FQBN                                
Arduino Nano 33 BLE                     arduino:mbed_nano:nano33ble         
Arduino Nano RP2040 Connect             arduino:mbed_nano:nanorp2040connect 
Arduino Primo                           arduino:nrf52:primo                 
Arduino Primo Core                      arduino:nrf52:primo_core            
littleBits w6 Arduino Module (Leonardo) littleBits:avr:w6_arduino           

% ./arduino-cli board listall
Board Name                              FQBN                                
Arduino Nano 33 BLE                     arduino:mbed_nano:nano33ble         
Arduino Nano RP2040 Connect             arduino:mbed_nano:nanorp2040connect 
Arduino Primo                           arduino:nrf52:primo                 
Arduino Primo Core                      arduino:nrf52:primo_core            
littleBits w6 Arduino Module (Leonardo) littleBits:avr:w6_arduino           

% ./arduino-cli board listall
Board Name                              FQBN                                
Arduino Nano 33 BLE                     arduino:mbed_nano:nano33ble         
Arduino Nano RP2040 Connect             arduino:mbed_nano:nanorp2040connect 
Arduino Primo                           arduino:nrf52:primo                 
Arduino Primo Core                      arduino:nrf52:primo_core            
littleBits w6 Arduino Module (Leonardo) littleBits:avr:w6_arduino           

% ./arduino-cli board listall
Board Name                              FQBN                                
Arduino Nano 33 BLE                     arduino:mbed_nano:nano33ble         
Arduino Nano RP2040 Connect             arduino:mbed_nano:nanorp2040connect 
Arduino Primo                           arduino:nrf52:primo                 
Arduino Primo Core                      arduino:nrf52:primo_core            
littleBits w6 Arduino Module (Leonardo) littleBits:avr:w6_arduino           

% ./arduino-cli board listall
Board Name                              FQBN                                
Arduino Nano 33 BLE                     arduino:mbed_nano:nano33ble         
Arduino Nano RP2040 Connect             arduino:mbed_nano:nanorp2040connect 
Arduino Primo                           arduino:nrf52:primo                 
Arduino Primo Core                      arduino:nrf52:primo_core            
littleBits w6 Arduino Module (Leonardo) littleBits:avr:w6_arduino           
```

Run the same command with the `--format json` flag at least twice (or multiple times), and you most likely get a different output than the previous one:
```
% ./arduino-cli board listall --format json
{
  "boards": [
    {
      "name": "Arduino Primo",
      "fqbn": "arduino:nrf52:primo",
      "platform": {
        "id": "arduino:nrf52",
        "installed": "1.0.2",
        "latest": "1.0.2",
        "name": "Arduino nRF52 Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "Arduino Primo Core",
      "fqbn": "arduino:nrf52:primo_core",
      "platform": {
        "id": "arduino:nrf52",
        "installed": "1.0.2",
        "latest": "1.0.2",
        "name": "Arduino nRF52 Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "Arduino Nano RP2040 Connect",
      "fqbn": "arduino:mbed_nano:nanorp2040connect",
      "platform": {
        "id": "arduino:mbed_nano",
        "installed": "3.2.0",
        "latest": "3.3.0",
        "name": "Arduino Mbed OS Nano Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "Arduino Nano 33 BLE",
      "fqbn": "arduino:mbed_nano:nano33ble",
      "platform": {
        "id": "arduino:mbed_nano",
        "installed": "3.2.0",
        "latest": "3.3.0",
        "name": "Arduino Mbed OS Nano Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "littleBits w6 Arduino Module (Leonardo)",
      "fqbn": "littleBits:avr:w6_arduino",
      "platform": {
        "id": "littleBits:avr",
        "installed": "1.0.0",
        "latest": "1.0.0",
        "name": "littleBits Arduino AVR Modules",
        "maintainer": "littleBits Electronics",
        "website": "http://www.littlebits.cc/bits/w6-arduino",
        "email": "support@littlebits.cc"
      }
    }
  ]
}
% ./arduino-cli board listall --format json
{
  "boards": [
    {
      "name": "Arduino Nano RP2040 Connect",
      "fqbn": "arduino:mbed_nano:nanorp2040connect",
      "platform": {
        "id": "arduino:mbed_nano",
        "installed": "3.2.0",
        "latest": "3.3.0",
        "name": "Arduino Mbed OS Nano Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "Arduino Nano 33 BLE",
      "fqbn": "arduino:mbed_nano:nano33ble",
      "platform": {
        "id": "arduino:mbed_nano",
        "installed": "3.2.0",
        "latest": "3.3.0",
        "name": "Arduino Mbed OS Nano Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "Arduino Primo",
      "fqbn": "arduino:nrf52:primo",
      "platform": {
        "id": "arduino:nrf52",
        "installed": "1.0.2",
        "latest": "1.0.2",
        "name": "Arduino nRF52 Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "Arduino Primo Core",
      "fqbn": "arduino:nrf52:primo_core",
      "platform": {
        "id": "arduino:nrf52",
        "installed": "1.0.2",
        "latest": "1.0.2",
        "name": "Arduino nRF52 Boards",
        "maintainer": "Arduino",
        "website": "http://www.arduino.cc/",
        "email": "packages@arduino.cc"
      }
    },
    {
      "name": "littleBits w6 Arduino Module (Leonardo)",
      "fqbn": "littleBits:avr:w6_arduino",
      "platform": {
        "id": "littleBits:avr",
        "installed": "1.0.0",
        "latest": "1.0.0",
        "name": "littleBits Arduino AVR Modules",
        "maintainer": "littleBits Electronics",
        "website": "http://www.littlebits.cc/bits/w6-arduino",
        "email": "support@littlebits.cc"
      }
    }
  ]
}
% 
```

### Arduino CLI version

c8ff0425

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by Bikappa**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?

Makes the `board listall` command output order consistent across formats. The list items are ordered by the package and platforms names they belong too, other than the board names themselves.
The plain text format remains an exception to this as it's sorted alphabetically by board name. 

## What is the current behavior?

In output formats other than plain text the board list is inconsistently ordered: while the boards within a single package/platform are ordered alphabetically they might appear before or after the ones of an other package/platform.

## What is the new behavior?

The list is ordered by package, platform and board names.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No

## Other information

Fixes #1909, although ordering between plain text and other formats remain different

### CODE REVIEW

File: commands/board/listall.go [hunk 1]
```diff
@@ -93,3 +95,37 @@ func ListAll(ctx context.Context, req *rpc.BoardListAllRequest) (*rpc.BoardListA
 
 	return list, nil
 }
+
+// TODO use a generic function instead of the two below once go >1.18 is adopted.
```
Comment (Bikappa) [inline commands/board/listall.go:99]: Let me know if this isn't the case, I did not find a nice way to do it in 1.17 but I'm far from a go guru

Comment (cmaglie) [reply commands/board/listall.go:99]: You did right it's not possible until we upgrade to go1.18+.

**Review by cmaglie — APPROVED** [review]
