### PR TITLE
Fix invalid JSON and YAML outputs for `outdated` command

### LINKED ISSUE #2104: Invalid JSON output for outdated command
### Describe the problem

When running the `outdated` command with `--format json`, the produced output is not valid JSON. It looks like it contains two arrays.

### To reproduce

Install an outdated library ie: 
```bash
arduino-cli lib install "FastLED@3.3.2"
```
Then run : 
```bash
arduino-cli --format json outdated
```
Which produces the following output : 
```json
[]
[
  {
    "library": {
      "name": "FastLED",
      "author": "Daniel Garcia",
      "maintainer": "Daniel Garcia \u003cdgarcia@fastled.io\u003e",
      "sentence": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "paragraph": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "website": "https://github.com/FastLED/FastLED",
      "category": "Display",
      "architectures": [
        "*"
      ],
      "install_dir": "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED",
      "source_dir": "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED",
      "version": "3.3.2",
      "license": "Unspecified",
      "location": 1,
      "examples": [
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\AnalogOutput",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Blink",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\ColorPalette",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\ColorTemperature",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Cylon",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\DemoReel100",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Fire2012",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Fire2012WithPalette",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\FirstLight",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\ArrayOfLedArrays",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\MirroringSample",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\MultiArrays",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\MultipleStripsInOneArray",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\OctoWS2811Demo",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\ParallelOutputDemo",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Noise",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\NoisePlayground",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\NoisePlusPalette",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Pintest",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Ports\\PJRCSpectrumAnalyzer",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\RGBCalibrate",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\RGBSetDemo",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\SmartMatrix",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\XYMatrix"
      ],
      "provides_includes": [
        "FastLED.h",
        "bitswap.h",
        "chipsets.h",
        "color.h",
        "colorpalettes.h",
        "colorutils.h",
        "controller.h",
        "cpp_compat.h",
        "dmx.h",
        "fastled_config.h",
        "fastled_delay.h",
        "fastled_progmem.h",
        "fastpin.h",
        "fastspi.h",
        "fastspi_bitbang.h",
        "fastspi_dma.h",
        "fastspi_nop.h",
        "fastspi_ref.h",
        "fastspi_types.h",
        "hsv2rgb.h",
        "led_sysdefs.h",
        "lib8tion.h",
        "noise.h",
        "pixelset.h",
        "pixeltypes.h",
        "platforms.h",
        "power_mgt.h"
      ]
    },
    "release": {
      "author": "Daniel Garcia",
      "version": "3.5.0",
      "maintainer": "Daniel Garcia \u003cdgarcia@fastled.io\u003e",
      "sentence": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "paragraph": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "website": "https://github.com/FastLED/FastLED",
      "category": "Display",
      "architectures": [
        "*"
      ],
      "types": [
        "Contributed"
      ]
    }
  }
]
```

### Expected behavior

The output should be valid JSON.

### Arduino CLI version

arduino-cli.exe  Version: nightly-20230310 Commit: fed439a Date: 2023-03-10T01:35:49Z

### Operating system

Windows

### Operating system version

Windows 11 22H2

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by lluiscampos**
Fixes issue #2104

The code for `internal/cli/core` and `internal/cli/lib` has been
refactored so that we can use only the `Get` functions from
`internal/cli/outdated` package and compose there composited object.

For regular text output, the new table will have some extra fields that
either for platforms or for libraries will be blank.

For JSON and YAML output, the resulting object will have the top-level
keys `platforms` and `libraries` which contain, respectively, the array
of outaded platforms and outdated libraries.

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

Fixes #2104

## What is the current behavior?

`outdated` commands prints two tables for text mode, and two objects for JSON mode:

Text (default):

```
>>> Running: /home/lluis/go/src/github.com/arduino/arduino-cli/arduino-cli outdated
ID          Installed Latest Name
arduino:avr 1.6.3     1.8.6  Arduino AVR Boards

Name    Installed     Available     Location              Description
USBHost 1.0.0         1.0.5         LIBRARY_LOCATION_USER Allows the communication with USB per...
```

and JSON:

```
$ arduino-cli outdated --format json
[]
[
  {
    "library": {
      "name": "FastLED",
      "author": "Daniel Garcia",
      "maintainer": "Daniel Garcia \u003cdgarcia@fastled.io\u003e",
      "sentence": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "paragraph": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "website": "https://github.com/FastLED/FastLED",
      "category": "Display",
      "architectures": [
        "*"
      ],
      "install_dir": "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED",
      "source_dir": "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED",
      "version": "3.3.2",
      "license": "Unspecified",
      "location": 1,
      "examples": [
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\AnalogOutput",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Blink",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\ColorPalette",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\ColorTemperature",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Cylon",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\DemoReel100",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Fire2012",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Fire2012WithPalette",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\FirstLight",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\ArrayOfLedArrays",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\MirroringSample",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\MultiArrays",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\MultipleStripsInOneArray",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\OctoWS2811Demo",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Multiple\\ParallelOutputDemo",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Noise",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\NoisePlayground",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\NoisePlusPalette",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Pintest",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\Ports\\PJRCSpectrumAnalyzer",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\RGBCalibrate",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\RGBSetDemo",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\SmartMatrix",
        "C:\\Users\\gaspa\\Documents\\Arduino\\libraries\\FastLED\\examples\\XYMatrix"
      ],
      "provides_includes": [
        "FastLED.h",
        "bitswap.h",
        "chipsets.h",
        "color.h",
        "colorpalettes.h",
        "colorutils.h",
        "controller.h",
        "cpp_compat.h",
        "dmx.h",
        "fastled_config.h",
        "fastled_delay.h",
        "fastled_progmem.h",
        "fastpin.h",
        "fastspi.h",
        "fastspi_bitbang.h",
        "fastspi_dma.h",
        "fastspi_nop.h",
        "fastspi_ref.h",
        "fastspi_types.h",
        "hsv2rgb.h",
        "led_sysdefs.h",
        "lib8tion.h",
        "noise.h",
        "pixelset.h",
        "pixeltypes.h",
        "platforms.h",
        "power_mgt.h"
      ]
    },
    "release": {
      "author": "Daniel Garcia",
      "version": "3.5.0",
      "maintainer": "Daniel Garcia \u003cdgarcia@fastled.io\u003e",
      "sentence": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "paragraph": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
      "website": "https://github.com/FastLED/FastLED",
      "category": "Display",
      "architectures": [
        "*"
      ],
      "types": [
        "Contributed"
      ]
    }
  }
]
```

## What is the new behavior?

`outdated` commands prints one merged table for text mode, and one object for JSON mode:

Text (default):

```
>>> Running: /home/lluis/go/src/github.com/arduino/arduino-cli/arduino-cli outdated
ID          Name               Installed Latest Location              Description
arduino:avr Arduino AVR Boards 1.6.3     1.8.6
            USBHost            1.0.0     1.0.5  LIBRARY_LOCATION_USER Allows the communication with USB per...
```

and JSON:

```
./arduino-cli outdated --format json
[
  [],
  [
    {
      "library": {
        "architectures": [
          "*"
        ],
        "author": "Daniel Garcia",
        "category": "Display",
        "examples": [
          "/home/lluis/Arduino/libraries/FastLED/examples/AnalogOutput",
          "/home/lluis/Arduino/libraries/FastLED/examples/Blink",
          "/home/lluis/Arduino/libraries/FastLED/examples/ColorPalette",
          "/home/lluis/Arduino/libraries/FastLED/examples/ColorTemperature",
          "/home/lluis/Arduino/libraries/FastLED/examples/Cylon",
          "/home/lluis/Arduino/libraries/FastLED/examples/DemoReel100",
          "/home/lluis/Arduino/libraries/FastLED/examples/Fire2012",
          "/home/lluis/Arduino/libraries/FastLED/examples/Fire2012WithPalette",
          "/home/lluis/Arduino/libraries/FastLED/examples/FirstLight",
          "/home/lluis/Arduino/libraries/FastLED/examples/Multiple/ArrayOfLedArrays",
          "/home/lluis/Arduino/libraries/FastLED/examples/Multiple/MirroringSample",
          "/home/lluis/Arduino/libraries/FastLED/examples/Multiple/MultiArrays",
          "/home/lluis/Arduino/libraries/FastLED/examples/Multiple/MultipleStripsInOneArray",
          "/home/lluis/Arduino/libraries/FastLED/examples/Multiple/OctoWS2811Demo",
          "/home/lluis/Arduino/libraries/FastLED/examples/Multiple/ParallelOutputDemo",
          "/home/lluis/Arduino/libraries/FastLED/examples/Noise",
          "/home/lluis/Arduino/libraries/FastLED/examples/NoisePlayground",
          "/home/lluis/Arduino/libraries/FastLED/examples/NoisePlusPalette",
          "/home/lluis/Arduino/libraries/FastLED/examples/Pintest",
          "/home/lluis/Arduino/libraries/FastLED/examples/Ports/PJRCSpectrumAnalyzer",
          "/home/lluis/Arduino/libraries/FastLED/examples/RGBCalibrate",
          "/home/lluis/Arduino/libraries/FastLED/examples/RGBSetDemo",
          "/home/lluis/Arduino/libraries/FastLED/examples/SmartMatrix",
          "/home/lluis/Arduino/libraries/FastLED/examples/XYMatrix"
        ],
        "install_dir": "/home/lluis/Arduino/libraries/FastLED",
        "license": "Unspecified",
        "location": 1,
        "maintainer": "Daniel Garcia \u003cdgarcia@fastled.io\u003e",
        "name": "FastLED",
        "paragraph": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
        "provides_includes": [
          "FastLED.h",
          "bitswap.h",
          "chipsets.h",
          "color.h",
          "colorpalettes.h",
          "colorutils.h",
          "controller.h",
          "cpp_compat.h",
          "dmx.h",
          "fastled_config.h",
          "fastled_delay.h",
          "fastled_progmem.h",
          "fastpin.h",
          "fastspi.h",
          "fastspi_bitbang.h",
          "fastspi_dma.h",
          "fastspi_nop.h",
          "fastspi_ref.h",
          "fastspi_types.h",
          "hsv2rgb.h",
          "led_sysdefs.h",
          "lib8tion.h",
          "noise.h",
          "pixelset.h",
          "pixeltypes.h",
          "platforms.h",
          "power_mgt.h"
        ],
        "sentence": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
        "source_dir": "/home/lluis/Arduino/libraries/FastLED",
        "version": "3.3.2",
        "website": "https://github.com/FastLED/FastLED"
      },
      "release": {
        "architectures": [
          "*"
        ],
        "author": "Daniel Garcia",
        "category": "Display",
        "maintainer": "Daniel Garcia \u003cdgarcia@fastled.io\u003e",
        "paragraph": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
        "sentence": "Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions.",
        "types": [
          "Contributed"
        ],
        "version": "3.4.0",
        "website": "https://github.com/FastLED/FastLED"
      }
    }
  ]
]
```

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No

## Other information

See comment in https://github.com/arduino/arduino-cli/issues/2104#issuecomment-1467678692

### CODE REVIEW

**Comment by lluiscampos** [comment]
The code is ready for review now. There are some test failures but I believe they are spurious errors due to upstream timeouts or other glitches.

Any feedback is welcome! Thanks

File: internal/cli/lib/list.go [hunk 1]
```diff
@@ -60,8 +60,20 @@ func runListCommand(args []string, all bool, updatable bool) {
 	List(instance, args, all, updatable)
 }
 
-// List lists all the installed libraries.
+// List gets and prints a list of installed libraries.
 func List(instance *rpc.Instance, args []string, all bool, updatable bool) {
+	installedLibs := GetList(instance, args, all, updatable)
+	PrintList(updatable, installedLibs)
```
Comment (cmaglie) [inline internal/cli/lib/list.go:66]: Same here, inline `PrintList` and remove the function.

**Review by lluiscampos — COMMENTED** [review]
> I've added some changes that I'd like to see implemented.

I followed up accordingly.
 
> This is a breaking change, the file `docs/UPGRADING.md` must be updated with a note describing the breaking change in the JSON output of the `outdated` command that will be effective in the following `0.32.0` release (an example with the old and new will be sufficient).

Right. I originally didn't consider it a breaking change being a bugfix. But you are technically right! I have added it now.

Additionally, I realized that this also fixes the YAML output (which was also two independent objects) so I noted that as well in the `UPGRADING.md` and the commit message.

> Thank you for the very good PR @lluiscampos!

Thank you for the swift review!

**Review by cmaglie — APPROVED** [review]
