### PR TITLE
Easier recovery from soft bricked native USB boards

### LINKED ISSUE #1943: Recovery of soft bricked native USB boards w/o double-tap impossible without port selection
### Describe the problem

The primary microcontrollers of many Arduino boards have USB capabilities (e.g., Leonardo, Micro, MKR). These boards often communicate directly between the primary microcontroller and PC rather than having a separate "bridge" interface chip that provides the USB capability needed to communicate with the computer (e.g., Uno, Mega).

Because the USB capabilities are implemented as part of the same program as the user's sketch code on these "native USB" boards, it is possible for the user's code to disable, interfere with, or break the USB communication with the computer. This is a common occurrence that should be expected as part of the experience of developing firmware for this type of board. That may be the expected outcome (e.g., putting the microcontroller to sleep) or an unexpected result of a bug. When this happens, the board no longer produces a USB CDC serial port. This can make it difficult to upload to the board since that port is used in the upload process (e.g., ["1200 bps touch"](https://arduino.github.io/arduino-cli/dev/platform-specification/#1200-bps-bootloader-reset)).

In order to facilitate the recovery from this "[soft bricked](https://en.wikipedia.org/wiki/Brick_(electronics)#Soft_brick)" state, some bootloaders have a feature where they run indefinitely on the second of two resets in quick succession (sometimes referred to as "[double-tap](https://docs.arduino.cc/tutorials/nano-33-ble-sense/cheat-sheet#forcing-bootloader)"). However, not all bootloaders have this capability. On the bootloaders without support for the "double-tap" mode, the bootloader runs only for a short time after a reset before timing out and exiting to the application. In this case it is necessary for the user to time the manual reset so that the upload process occurs while the bootloader is running. For a combined compile and upload operation, this is a bit tricky since the bootloader might time out during the compilation phase if the reset was done before starting the operation.

The standard recovery procedure for these boards, as documented [here](https://docs.arduino.cc/retired/getting-started-guides/ArduinoLeonardoMicro#uploading-code-to-the-leonardo-leonardo-eth-and-micro), is to wait until the tooling indicates the upload phase is starting, then manually reset the board. This worked fine in Arduino IDE 1.x because the "[wait for upload port](https://arduino.github.io/arduino-cli/dev/platform-specification/#1200-bps-bootloader-reset)" phase is triggered even when no port is selected. The appearance of the port produced by the bootloader running after the manual reset is detected during that phase and used for the upload. However, that "wait for upload port" phase is skipped entirely if no port is specified in the Arduino CLI upload command:

https://github.com/arduino/arduino-cli/blob/f23975438ca8ad6463fadf61e181c0bc03a20ae1/commands/upload/upload.go#L381-L383

This is the case in the upload command produced by Arduino IDE 2.x when no port is selected, as well as in `arduino-cli` command line commands which do not contain a `--port` flag.

For users of the command line, the most "correct" approach would be to do a manual reset while `arduino-cli board list --watch` is running to determine the address of the bootloader port, then specify that port via the `--port` flag (manually resetting the board during the upload phase as usual to cause the port to be available for the upload).

This is not possible for Arduino IDE 2.x users, leaving them with the workaround of selecting an arbitrary random serial port that happens to be present on their system in order to cause a serial port to be provided to Arduino CLI so that it will run the "wait for upload port" phase during the upload. Some users may not even have an available port to use for the workaround, and even for those who do have a port it is very hacky.

The final recourse would be to do a "Burn Bootloader" operation, not because there is any need to re-flash the bootloader, but because the operation also erases the problematic sketch application from the board. However, that is very complicated for the average user and also requires additional hardware they might not possess.

🐛 It is difficult or impossible for users to recover these boards from the "soft bricked" state.

#### Equipment

Native USB board that does not have "double-tap" support:

- [Leonardo](https://store.arduino.cc/products/arduino-leonardo-with-headers)
- [Micro](https://store.arduino.cc/products/arduino-micro)
- [Yun](https://store.arduino.cc/products/arduino-yun-rev-2)
- I would guess any of the other boards that use Arduino's "caterina" bootloader, but I haven't checked others.

#### Steps

1. "Soft brick" your board by uploading this sketch:
   ⚠ This will put the board into a state that is slightly difficult to recover from.
   ```cpp
   void setup() {
     noInterrupts();
   }
   void loop() {}
   ```
1. Upload any sketch to the board without having a port selected.
1. Press and release the reset button on the board as soon as the upload process starts.

🐛 The upload fails even though the board was in bootloader mode:

```text
Error during Upload: Failed uploading: no upload port provided
```

### Expected behavior

It is possible for users to easily recover their boards from the "soft brick" state by following [the standard recovery procedure](https://docs.arduino.cc/retired/getting-started-guides/ArduinoLeonardoMicro#uploading-code-to-the-leonardo-leonardo-eth-and-micro).

### Arduino CLI version

f2397543

### Operating system

Windows, Ubuntu

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

As I mentioned in the introduction, it is already possible for command line users to accomplish a recovery in a fairly straightforward (though lengthy) manner. So this is mostly a problem for Arduino IDE 2.x users (and any other application that works in a similar manner). So it might be that the fix should be made in Arduino IDE 2.x rather than Arduino CLI.

For example, Arduino IDE 2.x could always pass the last selected port to Arduino CLI (it does not do this now), which would allow [the standard recovery procedure](https://docs.arduino.cc/retired/getting-started-guides/ArduinoLeonardoMicro#uploading-code-to-the-leonardo-leonardo-eth-and-micro) to be performed with the addition of the following steps at the start:

1. Press the reset button on the board.
1. Quickly select the port from the "Board Selector" or **Tools > Port**" menu.

I thought it worth first investigating whether there is a way for this to be handled by Arduino CLI without the requirement of a port selection, since that would allow the standard recovery procedure to continue to be used by the users of all modern Arduino development software. I was able to perform [the standard recovery procedure](https://docs.arduino.cc/retired/getting-started-guides/ArduinoLeonardoMicro#uploading-code-to-the-leonardo-leonardo-eth-and-micro) after simply removing the `&& port.Protocol == "serial"` from [`commands/upload/upload.go#L381`](https://github.com/arduino/arduino-cli/blob/f23975438ca8ad6463fadf61e181c0bc03a20ae1/commands/upload/upload.go#L381), but of course that conditional is there because the "1200 bps touch" process is specific to serial ports.

---

This is more relevant now because previously a bug in Arduino IDE 2.x (https://github.com/arduino/arduino-ide/issues/770) caused the Upload operation to not be initiated when no port was selected, so the Upload operation never got to the stage when the "`Failed uploading: no upload port provided`" error was returned by Arduino CLI during these recovery attempts.

---

Originally reported at https://forum.arduino.cc/t/ide-2-0-wont-program-arduinos-that-need-to-be-put-into-bootloader-mode/1044198

#### Additional reports

- https://forum.arduino.cc/t/arduino-2-1-0-breaks-stm32-hidbootloader-setup/1123374

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by cmaglie**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

This PR should make it easier to recover from soft-bricked boards with native USB (in cases where the serial port is unavailable because the bootloader has a too-short timeout).

## What is the current behavior?

Trying the upload without a port selected would cause the upload to immediately fail, without leaving any room for the user to synchronize with the upload by tapping the reset button. See #1943 for more details.

## What is the new behavior?

The upload should wait a reasonable amount of time for the user to tap the reset button and make the bootloader avaiable.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No, in theory...

## Other information

Fix #1943

### CODE REVIEW

**Comment by umbynos** [comment]
CLI 0.32.2:
```
❰umberto❙~/Downloads/arduino-cli_test-2173-c626c5af87608b229e9993ddc68e60f59ee8d65d-git-snapshot_Linux_64bit❱✔≻ arduino-cli compile -b arduino:avr:micro -u soft_brick/ -p /dev/ttyACM0 
Sketch uses 3464 bytes (12%) of program storage space. Maximum is 28672 bytes.
Global variables use 149 bytes (5%) of dynamic memory, leaving 2411 bytes for local variables. Maximum is 2560 bytes.
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44


Used platform Version Path                                                        
arduino:avr   1.8.6   /home/umberto/.arduino15/packages/arduino/hardware/avr/1.8.6
❰umberto❙~/Downloads/arduino-cli_test-2173-c626c5af87608b229e9993ddc68e60f59ee8d65d-git-snapshot_Linux_64bit❱✔≻ ./arduino-cli board list
Port         Protocol Type              Board Name FQBN Core
/dev/ttyUSB0 serial   Serial Port (USB) Unknown             

❰umberto❙~/Downloads/arduino-cli_test-2173-c626c5af87608b229e9993ddc68e60f59ee8d65d-git-snapshot_Linux_64bit❱✔≻ arduino-cli compile -b arduino:avr:micro /opt/arduino-1.8.13/examples/01.Basics/Blink/Blink.ino -u
Sketch uses 3958 bytes (13%) of program storage space. Maximum is 28672 bytes.
Global variables use 149 bytes (5%) of dynamic memory, leaving 2411 bytes for local variables. Maximum is 2560 bytes.
Error during Upload: Failed uploading: no upload port provided
```
CLI from this PR:
```
./arduino-cli compile -b arduino:avr:micro -u soft_brick/ -p /dev/ttyACM0
Sketch uses 3464 bytes (12%) of program storage space. Maximum is 28672 bytes.
Global variables use 149 bytes (5%) of dynamic memory, leaving 2411 bytes for local variables. Maximum is 2560 bytes.
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44


Used platform Version Path                                                        
arduino:avr   1.8.6   /home/umberto/.arduino15/packages/arduino/hardware/avr/1.8.6
❰umberto❙~/Downloads/arduino-cli_test-2173-c626c5af87608b229e9993ddc68e60f59ee8d65d-git-snapshot_Linux_64bit❱✔≻ ./arduino-cli board list
Port         Protocol Type              Board Name FQBN Core
/dev/ttyUSB0 serial   Serial Port (USB) Unknown             

❰umberto❙~/Downloads/arduino-cli_test-2173-c626c5af87608b229e9993ddc68e60f59ee8d65d-git-snapshot_Linux_64bit❱✔≻ ./arduino-cli compile -b arduino:avr:micro /opt/arduino-1.8.13/examples/01.Basics/Blink/Blink.ino -u
Sketch uses 3958 bytes (13%) of program storage space. Maximum is 28672 bytes.
Global variables use 149 bytes (5%) of dynamic memory, leaving 2411 bytes for local variables. Maximum is 2560 bytes.
Skipping 1200-bps touch reset: no serial port selected!
Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44


Used platform Version Path                                                        
arduino:avr   1.8.6   /home/umberto/.arduino15/packages/arduino/hardware/avr/1.8.6

File: commands/upload/upload.go [hunk 1]
```diff
@@ -361,11 +361,24 @@ func runProgramAction(pme *packagemanager.Explorer,
...
 	}
 
+	// Force port wait to make easier to unbrick boards like the Arduino Leonardo, or similar with native USB,
+	// when a sketch causes a crash and the native USB serial port is lost.
+	// See https://github.com/arduino/arduino-cli/issues/1943 for the details.
+	//
+	// In order to trigger the forced serial-port-wait the following conditions must be met:
+	// - No upload port specified (protocol == "default")
+	// - "upload.wait_for_upload_port" == true (developers requested the touch + port wait)
+	// - "upload.tool.serial" not defained, or
```
Comment (umbynos) [inline commands/upload/upload.go:371]:
```suggestion
	// - "upload.tool.serial" not defined, or
```
typo

**Review by umbynos — APPROVED** [review]

**Review by umbynos — APPROVED** [review]
