### PR TITLE
Now `compile --only-compilation-database` will run all pre-* hooks

### LINKED ISSUE #1547: Unable to generate only the compilation database
## Bug Report

### Current behavior

```
/home/linuxbrew/.linuxbrew/bin/arduino-cli --config-file /home/jacquesg/.arduino15/arduino-cli.yaml compile --fqbn esp32:esp32:featheresp32 --only-compilation-database --clean --build-path $PWD/build --format json /home/jacquesg/dev/AdvancedWebServer
{                                                                                                                                                                                                         
  "compiler_out": "",                                                                                                                                                                                     
  "compiler_err": "xtensa-esp32-elf-g++: error: /home/jacquesg/dev/AdvancedWebServer/build/build_opt.h: No such file or directory\n",                                                                     
  "builder_result": {                                                                                                                                                                                     
    "build_path": "/home/jacquesg/dev/AdvancedWebServer/build"                                                                                                                                            
  },                                                                                                                                                                                                      
  "success": false                                                                                                                                                                                        
} 
```

```
/home/linuxbrew/.linuxbrew/bin/arduino-cli --config-file /home/jacquesg/.arduino15/arduino-cli.yaml compile --fqbn esp32:esp32:featheresp32 --clean --build-path $PWD/build --format json /home/jacquesg/dev/AdvancedWebServer                                                                                                                                                     
{                                                                                                                                                                                                         
  "compiler_out": "Sketch uses 701109 bytes (53%) of program storage space. Maximum is 1310720 bytes.\nGlobal variables use 39840 bytes (12%) of dynamic memory, leaving 287840 bytes for local variables.
 Maximum is 327680 bytes.\n",                                                                                                                                                                             
  "compiler_err": "",
... SNIP ...
  },
  "success": true
}
```

From the above, by only requesting the compilation database the compilation fails.

### Expected behavior

No error should be generated.

### Environment

- CLI version (output of `arduino-cli version`): arduino-cli alpha Version: 0.19.3 Commit: 12f1afc2 Date: 2021-10-11T15:14:04Z
- OS and platform: Linux with an ESP32 board

### PR DESCRIPTION
**Pull request by cmaglie**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls) before creating one)
- [x] The PR follows [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**
To generate the "Compilation Database" some platforms requires to run the pre-build hooks to actually have a compilable target.

- **What is the current behavior?**
The pre-hooks are skipped.

* **What is the new behavior?**
The pre-hooks are now executed.

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**
It may introduce some regression if a platform requires skipping pre-hooks to actually build a sketch. This is very unlikely BTW, since this would make fail also the full compile.

* **Other information**:
The **post hooks** and the **compiler commands** are still SKIPPED.

Fix #1547

### CODE REVIEW

File: cli/compile/compile.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func NewCommand() *cobra.Command {
 	command.RegisterFlagCompletionFunc("programmer", func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
 		return arguments.GetInstalledProgrammers(), cobra.ShellCompDirectiveDefault
 	})
-	command.Flags().BoolVar(&compilationDatabaseOnly, "only-compilation-database", false, tr("Just produce the compilation database, without actually compiling."))
+	command.Flags().BoolVar(&compilationDatabaseOnly, "only-compilation-database", false, tr("Just produce the compilation database, without actually compiling. All build commands are skipped except all the pre-* hooks."))
```
Comment (per1234) [inline cli/compile/compile.go:115]:
```suggestion
	command.Flags().BoolVar(&compilationDatabaseOnly, "only-compilation-database", false, tr("Just produce the compilation database, without actually compiling. All build commands are skipped except pre* hooks."))
```
- Make more concise
- Remove the hyphen from hook pattern to match [the property names](https://arduino.github.io/arduino-cli/dev/platform-specification/#pre-and-post-build-hooks-since-arduino-ide-165)

File: docs/platform-specification.md [hunk 2]
```diff
@@ -399,6 +399,10 @@ recipe.hooks.sketch.prebuild.02.pattern=echo 2
 recipe.hooks.sketch.prebuild.11.pattern=echo 11
 ```
 
+Note: all the `pre*` hooks are executed also to produce the "compilation database" (it's a json file with the list of
+commands to run to compile the sketch), instead all the `post*` hooks and all compile commands will be skipped. See the
+[`arduino-cli compile`](commands/arduino-cli_compile.md) command for more info.
```
Comment (per1234) [inline docs/platform-specification.md:404]:
```suggestion
Note: all the `pre*` hooks are executed while producing the "compilation database" (a JSON file with the list of
commands to run to compile the sketch), but the `post*` hooks and all compile commands are skipped. See the
[`arduino-cli compile`](commands/arduino-cli_compile.md) command reference for more info.
```

Minor rewording.

File: test/test_compile_part_4.py [hunk 3]
```diff
@@ -292,6 +292,22 @@ def test_compile_with_esp8266_bundled_libraries(run_command, data_dir, copy_sket
...
 
 
+def test_generate_compile_commands_json_with_esp32(run_command, data_dir, copy_sketch):
+    # https://github.com/arduino/arduino-cli/issues/1547
+    assert run_command(["update"])
+
+    # Update index with esp32 core and install it
+    url = "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
+    assert run_command(["core", "update-index", f"--additional-urls={url}"])
+    assert run_command(["core", "install", "esp32:esp32", f"--additional-urls={url}"])
```
Comment (per1234) [inline test/test_compile_part_4.py:302]:
```suggestion
    assert run_command(["core", "install", "esp32:esp32@2.0.1", f"--additional-urls={url}"])
```
I think it is safest to pin to a version of the boards platform we know will produce the conditions required for an effective test.

File: test/test_compile_part_4.py [hunk 4]
```diff
@@ -292,6 +292,22 @@ def test_compile_with_esp8266_bundled_libraries(run_command, data_dir, copy_sket
...
+
+    # Install a library with the same name as one bundled with the core
+    assert run_command(["lib", "install", "SD"])
+
```
Comment (per1234) [inline test/test_compile_part_4.py:306]:
```suggestion
```
The SD library doesn't appear to be used by the test.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: test/test_compile_part_4.py [hunk 5]
```diff
@@ -292,6 +292,22 @@ def test_compile_with_esp8266_bundled_libraries(run_command, data_dir, copy_sket
     assert "\n".join(expected_output) not in res.stdout
 
 
+def test_generate_compile_commands_json_with_esp32(run_command, data_dir, copy_sketch):
+    # https://github.com/arduino/arduino-cli/issues/1547
+    assert run_command(["update"])
+
+    # Update index with esp32 core and install it
+    url = "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
```
[the remark this answers is not in the document]
Comment (cmaglie) [reply test/test_compile_part_4.py:300]: In that case, we should also cache the tools and the cores that may be removed in the future...

BTW I would not care now, we never had this problem before. IMHO we can just pin the version as suggested by @per1234, if the index.json or the core is removed it will make the test fail and we will take action only then.

File: docs/platform-specification.md (hunk 2 above)
Comment (cmaglie) [reply docs/platform-specification.md]: Thanks for the proofreading!

**Review by per1234 — APPROVED** [review]
I'm not knowledgeable about the compilation database subject, but I was able to reproduce https://github.com/arduino/arduino-cli/issues/1547 for both `esp32:esp32` and `STMicroelectronics:stm32` boards platforms previously and am not able to reproduce it after the change proposed here.
