### PR TITLE
[breaking] fix: validate sketch name

### LINKED ISSUE #2043: The `sketch new` command ignores the sketch folder name specification
### Describe the problem

I can use the CLI `sketch new` to create invalid sketches which will not compile. The little sister task of this one is arduino/arduino-ide#1599.

### To reproduce

```
./arduino-cli version                                                          
arduino-cli  Version: git-snapshot Commit: a58d5adb Date: 2023-01-23T09:37:23Z
```

```
./arduino-cli sketch new "/Users/a.kitta/Documents/Arduino/\`~%^&()=+[{]};',.cpp"
Sketch created in: /Users/a.kitta/Documents/Arduino/`~%^&()=+[{]};',.cpp
```

```
cat ~/Documents/Arduino/\`\~%\^\&\(\)=+\[\{\]\}\;\',.cpp/\`\~%\^\&\(\)=+\[\{\]\}\;\',.cpp.ino

void setup() {
}

void loop() {
}
```

```
./arduino-cli compile -b arduino:avr:uno  "/Users/a.kitta/Documents/Arduino/\`~%^&()=+[{]};',.cpp"
avr-g++: error: /private/var/folders/z1/xkw1yh5n7rz4n8djprp1mdn80000gn/T/arduino/sketch-94408ACC1CA44D8729BBBE1057EBD2E8/sketch/`~%^&()=+[;',.cpp.ino.cpp: No such file or directory
avr-g++: warning: '-x c++' after last input file has no effect
avr-g++: fatal error: no input files
compilation terminated.

Used platform Version Path                                                                
arduino:avr   1.8.6   /Users/a.kitta/Library/Arduino15/packages/arduino/hardware/avr/1.8.6
Error during build: exit status 1
```

### Expected behavior

`new sketch` fails when the sketch's name is invalid. https://arduino.github.io/arduino-cli/dev/sketch-specification/#sketch-root-folder

### Arduino CLI version

a58d5adb

### Operating system

macOS

### Operating system version

12.5.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by Bikappa**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?

It alignes the validation of sketch names to the documentation
https://arduino.github.io/arduino-cli/dev/sketch-specification/#sketch-folders-and-files
Sketch creation request that don't respect the validation rules are rejected

## What is the current behavior?

No validation is performed on the sketch name

## What is the new behavior?

Sketch names that don't respect the required pattern, consisting in alphanumeric characters, dots, underscores and dashes, or that are longer 
than 63 characters cause the request to be rejected.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

Yes! Freeform sketch names that were in use before will not be compatible anymore.

## Other information

Fixes #2043

### CODE REVIEW

**Comment by Bikappa** [comment]
Possibly duplicate of #2049

**Comment by per1234** [comment]
I'll reopen this since the PR https://github.com/arduino/arduino-cli/pull/2049 of the prior proposal was closed by @cushonz

**Review by umbynos — APPROVED** [review]
Code LGTM, l would wait for a review by @per1234 before merging, just to be sure we did not left out anything

File: commands/sketch/new.go [hunk 1]
```diff
@@ -34,6 +35,10 @@ void loop() {
 }
 `)
 
+// sketchNameMaxLength could be part of the regex, but it's intentionally left out for clearer error reporting
+var sketchNameMaxLength = 63
+var sketchNameValidationRegex = regexp.MustCompile(`^[0-9a-zA-Z]{1}[0-9a-zA-Z_\.-]*$`)
```
Comment (per1234) [inline commands/sketch/new.go:40]:
```suggestion
var sketchNameValidationRegex = regexp.MustCompile(`^[0-9a-zA-Z][0-9a-zA-Z_\.-]*$`)
```

The `{1}` is superfluous. It made sense for the sake of consistency in the Arduino IDE regex, which also enforces the maximum length, but this regex doesn't do that.

Since the regex is exposed to the user in the error message, I think having the less obvious and less common quantifier syntax in the regex makes the error message more difficult to understand for a user without a good knowledge of regular expressions.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: commands/sketch/new.go (hunk 1 above)
Comment (Bikappa) [reply commands/sketch/new.go:40]: Should be better now, I also found out empty sketch names were not really handled before. Now they are

Comment (per1234) [reply commands/sketch/new.go:40]: @Bikappa the regex is still the same as it was when I did my review.

File: internal/integrationtest/sketch/sketch_test.go [hunk 2]
```diff
@@ -73,6 +73,16 @@ func TestSketchNew(t *testing.T) {
 	require.FileExists(t, currentSketchPath.Join(sketchName).String()+".ino")
 }
 
+func TestSketchNewEmptyName(t *testing.T) {
+	// testing that we fail nicely. It panicked in the past
+	env, cli := integrationtest.CreateArduinoCLIWithEnvironment(t)
+	defer env.CleanUp()
+
+	sketchName := `Can't create sketch: sketch name cannot be empty`
```
Comment (per1234) [inline internal/integrationtest/sketch/sketch_test.go:81]:
```suggestion
	sketchName := ""
```

**Review by per1234 — CHANGES_REQUESTED** [review]

File: commands/sketch/new.go (hunk 1 above)
Comment (Bikappa) [reply commands/sketch/new.go]: Should be gone for real now

**Review by per1234 — APPROVED** [review]
Thanks Luca!

File: commands/sketch/new.go [hunk 3]
```diff
@@ -59,3 +69,20 @@ func NewSketch(ctx context.Context, req *rpc.NewSketchRequest) (*rpc.NewSketchRe
 
 	return &rpc.NewSketchResponse{MainFile: sketchMainFilePath.String()}, nil
 }
+
+func validateSketchName(name string) error {
+	if name == "" {
+		return &arduino.CantCreateSketchError{Cause: errors.New(tr("sketch name cannot be empty"))}
+	}
+	if len(name) > sketchNameMaxLength {
+		return &arduino.CantCreateSketchError{Cause: errors.New(tr("sketch name too long (%d characters). Maximum allowed length is %d",
```
Comment (cmaglie) [inline commands/sketch/new.go:78]: `"sketch name too long (%d characters). Maximum allowed length is %d"`
This string has 2 positional parameters, you must replace `%d` with `%[1]d` and `%[2]d`.
This would normally not be a problem, but since it's translated into another language with `tr(...)`, the ordering of the parameters is not guaranteed to stay the same.

File: commands/sketch/new.go [hunk 4]
```diff
@@ -59,3 +69,20 @@ func NewSketch(ctx context.Context, req *rpc.NewSketchRequest) (*rpc.NewSketchRe
...
+			len(name),
+			sketchNameMaxLength))}
+	}
+	if !sketchNameValidationRegex.MatchString(name) {
+		return &arduino.CantCreateSketchError{Cause: errors.New(tr("invalid sketch name \"%s\". Required pattern %s",
```
Comment (cmaglie) [inline commands/sketch/new.go:83]: This error outputs: `invalid sketch name "xxx". Required pattern ^[0-9a-zA-Z][0-9a-zA-Z_\.-]*$`
Not everyone is able to digest a regex, maybe a little explanation is better:
`invalid sketch name "xxx": the first character must be alphanumeric, the following ones can also contain "_", "-", and ".".`
