### PR TITLE
fix: discovery cleanup and watchers continuity upon core install 

### LINKED ISSUE #1588: The `BoardListWatch` process must not be stopped when installing/uninstalling/upgrading a core or library
### Current behavior

The `BoardListWatch` process is stopped each time a client calls the `Init` directly or indirectly from another gRPC function.
This makes it hard for gRPC clients to handle the `BoardListWatch` process.

### Expected behavior

The `BoardListWatch` process never stops after is started by a gRPC client, but handles gracefully and transparently the `Init`ialization of the CLI internal `Instance`.

### Environment

- CLI version (output of `arduino-cli version`): `0.20.2`
- OS and platform: Any

### Additional context

This is related to #1587, #1460, and arduino/arduino-ide#674.

The arduino/arduino-ide#674 is a fast workaround to handle #1587 and another issue only reported by @ubidefeo that stops the discovery processes on the IDE even though the `quit` event mentioned in #1587 is sent correctly.

When this issue will be fixed we can remove the arduino/arduino-ide#674 workaround.

### LINKED ISSUE #1960: Previous custom discovery tool process left running after update
### Describe the problem

In addition to the always available [**serial-discovery**](https://github.com/arduino/serial-discovery) and [**mdns-discovery**](https://github.com/arduino/mdns-discovery) [pluggable discovery](https://arduino.github.io/arduino-cli/dev/pluggable-discovery-specification/) tools of the `builtin` package, dependencies on custom discovery tools [can be specified](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/#tools-definitions:~:text=discoveryDependencies%3A%20the%20Pluggable%20Discoveries%20needed%20by%20this%20platform) by boards platforms.

[The latest version of the custom discovery dependency is installed](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/#tools-definitions:~:text=the%20latest%20installed%20discovery%20tool%20will%20always%20be%20used) when installing or updating that platform.

🐛 The process for the previous version of a custom discovery tool is left running after a boards platform update that updates the discovery tool.

#### Setup

```text
$ arduino-cli version

arduino-cli  Version: git-snapshot Commit: 732bdc54 Date: 2022-09-07T09:00:01Z

$ export ARDUINO_DIRECTORIES_DATA="/tmp/arduino-cli-directories/data"

$ export ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS="https://www.pjrc.com/teensy/package_teensy_index.json"

$ arduino-cli core update-index

$ arduino-cli core install teensy:avr@1.57.0  # Install outdated version of a platform with custom pluggable discovery tool dependency

[...]
Installing teensy:teensy-discovery@1.57.1...
teensy:teensy-discovery@1.57.1 installed
[...]

$ mv "${ARDUINO_DIRECTORIES_DATA}/packages/teensy/tools/teensy-discovery/1.57.1" "${ARDUINO_DIRECTORIES_DATA}/packages/teensy/tools/teensy-discovery/1.57.0"  # Simulate outdated discovery tool

$ arduino-cli daemon --debug

Daemon is now listening on 127.0.0.1:50051
```

#### Demo

run the following [`grpcurl`](https://github.com/fullstorydev/grpcurl) commands in another terminal:

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Create

{
  "instance": {
    "id": 1
  }
}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Init

$ pgrep -a -f 'teensy-discovery'

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.BoardListWatch

[...]

$ pgrep -a -f 'teensy-discovery'

142276 /tmp/arduino-cli-directories/data/packages/teensy/tools/teensy-discovery/1.57.0/teensy-discovery

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}, "platform_package": "teensy", "architecture": "avr", "version": "1.57.1"}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.PlatformInstall

[...]

{
  "taskProgress": {
    "name": "Installing teensy:teensy-discovery@1.57.1"
  }
}

[...]

$ pgrep -a -f 'teensy-discovery'

142276 /tmp/arduino-cli-directories/data/packages/teensy/tools/teensy-discovery/1.57.0/teensy-discovery

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.BoardListWatch

[...]

$ pgrep -a -f 'teensy-discovery'

142276 /tmp/arduino-cli-directories/data/packages/teensy/tools/teensy-discovery/1.57.0/teensy-discovery
142363 /tmp/arduino-cli-directories/data/packages/teensy/tools/teensy-discovery/1.57.1/teensy-discovery
```

🐛 There is a leftover `teensy:teensy-discovery@1.57.0` process still running in addition to `teensy:teensy-discovery@1.57.1`.

### Expected behavior

Discovery tool processes are cleaned up.

### Arduino CLI version

732bdc54

### Operating system

Windows, Ubuntu

### Operating system version

Windows 10, Ubuntu 20.04

### Additional context

Originally reported by @PaulStoffregen at https://forum.pjrc.com/threads/71370-Teensy4-1-reading-from-Serial-Monitor-of-Arduino-IDE?p=315184#post315184

---

I can also reproduce the issue using the equivalent command line interface commands. I chose to use the gRPC interface for the demo because the command line version seems unlikely to occur in real world usage, while the gRPC version is a simplification of an existing real world occurrence in Arduino IDE 2.x.

---

I suspected a similar problem might apply to the pluggable monitor tools (e.g., **teensy-monitor**). I did a quick check using Arduino IDE 2.x and found that only the previously running **teensy-monitor** process was running after the update. After I closed and reopened Serial Monitor, only a single **teensy-monitor** process for the updated version was running.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by Bikappa**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?

It introduces a teardown of the running discovery processes when installing a new core, restarting them after to keep the watchers receiving events.

## What is the current behavior?

When a new core is installed the running discovery processes are not terminated. Alive watchers freeze and don't receive any new events.

## What is the new behavior?

When a new core is installed all running discovery processes are terminated, also those not interested by the update. They are restarted after the installation completed and watchers are reconnected to the new stream of events.

Connected boards face first a "remove" and then an "add" event.

## Other information

Fixes #1960
Fixes #1588

### CODE REVIEW

File: commands/instances.go [hunk 1]
```diff
@@ -451,6 +458,19 @@ func Init(req *rpc.InitRequest, responseCallback func(r *rpc.InitResponse)) erro
...
 }
 
+func areDiscoveriesRunning(pm *packagemanager.PackageManager) bool {
+	if pm == nil {
+		return false
+	}
+	exp, release := pm.NewExplorer()
+	defer release()
+
+	if exp.DiscoveryManager() != nil && exp.DiscoveryManager().AreDiscoveriesRunning() {
```
Comment (Bikappa) [inline commands/instances.go:468]: please let me know if there's a simpler way to get the status

File: arduino/discovery/discoverymanager/discoverymanager.go [hunk 2]
```diff
@@ -65,9 +65,15 @@ func (dm *DiscoveryManager) Clear() {
 			logrus.Infof("Closed and removed discovery %s", d.GetID())
 		}
 	}
+	dm.discoveriesRunning = false
```
Comment (cmaglie) [inline arduino/discovery/discoverymanager/discoverymanager.go:68]:
```suggestion
```

this is wrong, if the `discoverymanager` is started it should be kept started, see my other comments

File: arduino/cores/packagemanager/package_manager.go [hunk 3]
```diff
@@ -93,7 +93,11 @@ func (pmb *Builder) BuildIntoExistingPackageManager(target *PackageManager) {
 	target.tempDir = pmb.tempDir
 	target.packagesCustomGlobalProperties = pmb.packagesCustomGlobalProperties
 	target.profile = pmb.profile
-	target.discoveryManager = pmb.discoveryManager
+	if target.discoveryManager != nil {
+		target.discoveryManager.Clear()
+	} else {
+		target.discoveryManager = pmb.discoveryManager
+	}
```
Comment (cmaglie) [inline arduino/cores/packagemanager/package_manager.go:100]: I think here:
* `target.discoveryManager` must be always `Clear()` (it cannot be `nil` by construction)
* the discoveries in `pmb.discoveryManager` must be all added to `target.discoveryManager`

```go
	target.discoveryManager.Clear()
	target.discoveryManager.AddAllDiscoveriesFrom(pmb.discoveryManager)
```

I think the only thing you need to implement is the method `AddAllDiscoveriesFrom(...)`.
This would solve also the problem with `areDiscoveriesRunning` because you don't need to track if the discoveries are started: in either case, the original discoverymanager will handle them correctly once they are `Add()`-ed.

File: commands/instances.go (hunk 1 above)
Comment (cmaglie) [reply commands/instances.go:468]: It is not needed, see my other comments.

**Review by cmaglie — CHANGES_REQUESTED** [review]

File: arduino/discovery/discoverymanager/discoverymanager.go [hunk 4]
```diff
@@ -276,3 +277,14 @@ func (dm *DiscoveryManager) List() []*discovery.Port {
...
+
+// AddAllDiscoveriesFrom transfers discoveries from src to the receiver
+func (dm *DiscoveryManager) AddAllDiscoveriesFrom(src *DiscoveryManager) {
+	for id, d := range src.discoveries {
+		dm.discoveries[id] = d
+	}
+
+	if src.discoveriesRunning {
+		dm.Start()
+	}
```
Comment (cmaglie) [inline arduino/discovery/discoverymanager/discoverymanager.go:289]:
```suggestion
	for id, d := range src.discoveries {
		dm.Add(d)
	}
```

File: commands/instances.go [hunk 5]
```diff
@@ -268,6 +268,9 @@ func Init(req *rpc.InitRequest, responseCallback func(r *rpc.InitResponse)) erro
 		// after reinitializing an instance after installing or uninstalling a core.
 		// If this is not done the information of the uninstall core is kept in memory,
 		// even if it should not.
+
+		// register whether the discoveries are running, if so we need to start them in
+		// order for the previous watchers to keep receiving events
```
Comment (cmaglie) [inline commands/instances.go:273]: Leftover comment

```suggestion
```

File: arduino/cores/packagemanager/package_manager.go [hunk 6]
```diff
@@ -93,7 +93,12 @@ func (pmb *Builder) BuildIntoExistingPackageManager(target *PackageManager) {
...
+	target.discoveryManager.AddAllDiscoveriesFrom(pmb.discoveryManager)
```
Comment (cmaglie) [inline arduino/cores/packagemanager/package_manager.go:101]: `target.discoveryManager` can't be `nil` by construction

```suggestion
	target.discoveryManager.Clear()
	target.discoveryManager.AddAllDiscoveriesFrom(pmb.discoveryManager)
```

**Review by cmaglie — CHANGES_REQUESTED** [review]

File: arduino/cores/packagemanager/package_manager.go (hunk 6 above)
Comment (Bikappa) [reply arduino/cores/packagemanager/package_manager.go:101]: I tried to remove it but got a `runtime error: invalid memory address or nil pointer dereference` on the first initialization

Comment (Bikappa) [reply arduino/cores/packagemanager/package_manager.go:106]: The empty target is coming from https://github.com/arduino/arduino-cli/blob/master/arduino/cores/packagemanager/package_manager.go#L107

**Review by cmaglie — APPROVED** [review]
