### PR TITLE
Sample command to solve compile or upload issue is now shown to CLI users

### LINKED ISSUE #1356: Provide sample command to install missing platform
As of now, when trying to compile or upload to a platform that is not installed, the following error is returned:

```
Error during Upload: incorrect FQBN: platform arduino:avr is not installed
```

It could be nice to help users by providing the command they can run to fix the issue:

```
Error during Upload: incorrect FQBN: platform arduino:avr is not installed; try running `arduino-cli core install arduino:avr`
```

(It would be even better to prompt user to install the platform, but this would break the current non-interactive behavior of arduino-cli)

### PR DESCRIPTION
**Pull request by silvanocerza**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Enhances certain error messages of `compile` and `upload` commands.

- **What is the current behavior?**

```
$ arduino-cli core list


$ arduino-cli compile -b arduino:samd:nano_33_iot ~/Arduino/Blink

Error during build: Platform 'arduino:samd' not found: platform not installed

$ arduino-cli compile -b adafruit:samd:adafruit_feather_m4 ~/Arduino/Blink

Error during build: Platform 'adafruit:samd' not found: platform not installed

$ arduino-cli upload -b arduino:samd:nano_33_iot ~/Arduino/Blink -p /dev/ttyACM1
Error during Upload: Unknown FQBN: platform arduino:samd is not installed

$ arduino-cli upload -b adafruit:samd:adafruit_feather_m4 ~/Arduino/Blink -p /dev/ttyACM1
Error during Upload: Unknown FQBN: unknown package adafruit
```

* **What is the new behavior?**

```
$ arduino-cli core list


$ arduino-cli compile -b arduino:samd:nano_33_iot ~/Arduino/Blink

Error during build: Platform 'arduino:samd' not found: platform not installed
Try running `arduino-cli core install arduino:samd`

$ arduino-cli compile -b adafruit:samd:adafruit_feather_m4 ~/Arduino/Blink

Error during build: Platform 'adafruit:samd' not found: platform not installed
Platform adafruit:samd is not found in any known index

$ arduino-cli upload -b arduino:samd:nano_33_iot ~/Arduino/Blink -p /dev/ttyACM1
Error during Upload: Platform 'arduino:samd' not found: platform arduino:samd is not installed
Try running `arduino-cli core install arduino:samd`

$ arduino-cli upload -b adafruit:samd:adafruit_feather_m4 ~/Arduino/Blink -p /dev/ttyACM1
Error during Upload: Platform 'adafruit:samd' not found: unknown package adafruit
Platform adafruit:samd is not found in any known index
```

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Nope.

* **Other information**:

Closes #1356.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

File: cli/upload/upload.go [hunk 1]
```diff
@@ -109,6 +115,28 @@ func runUploadCommand(command *cobra.Command, args []string) {
...
+				Package:              split[0],
+				PlatformArchitecture: split[1],
+			})
+
+			if platform != nil {
+				feedback.Errorf(tr("Try running `%s core install %s`", globals.VersionInfo.Application, platformErr.Platform))
+			} else {
+				feedback.Errorf(tr("Platform %s is not found in any known index", platformErr.Platform))
+			}
+		}
```
Comment (umbynos) [inline cli/upload/upload.go:139]: the code is the same as in `compile.go`. But I would't know where to put it

File: cli/compile/compile.go [hunk 2]
```diff
@@ -264,6 +269,28 @@ func runCompileCommand(cmd *cobra.Command, args []string) {
 	})
 	if compileError != nil && output.OutputFormat != "json" {
```
Comment (umbynos) [inline cli/compile/compile.go:270]: All the added logic happens if `output.OutputFormat != "json"`, this means that no error is returned in case the output is json

File: cli/compile/compile.go [hunk 3]
```diff
@@ -264,6 +269,28 @@ func runCompileCommand(cmd *cobra.Command, args []string) {
...
+			}
+
+			pm := commands.GetPackageManager(inst.GetId())
+			platform := pm.FindPlatform(&packagemanager.PlatformReference{
+				Package:              split[0],
+				PlatformArchitecture: split[1],
+			})
+
+			if platform != nil {
+				feedback.Errorf(tr("Try running `%s core install %s`", globals.VersionInfo.Application, platformErr.Platform))
```
Comment (per1234) [inline cli/compile/compile.go:289]:
```suggestion
				feedback.Errorf(tr("Try running %s", fmt.Sprintf("`%s core install %s`", globals.VersionInfo.Application, platformErr.Platform)))
```
This will avoid the "core" and "install" being mistaken as words to translate.

File: cli/upload/upload.go [hunk 4]
```diff
@@ -109,6 +115,28 @@ func runUploadCommand(command *cobra.Command, args []string) {
...
+			}
+
+			pm := commands.GetPackageManager(instance.GetId())
+			platform := pm.FindPlatform(&packagemanager.PlatformReference{
+				Package:              split[0],
+				PlatformArchitecture: split[1],
+			})
+
+			if platform != nil {
+				feedback.Errorf(tr("Try running `%s core install %s`", globals.VersionInfo.Application, platformErr.Platform))
```
Comment (per1234) [inline cli/upload/upload.go:135]:
```suggestion
				feedback.Errorf(tr("Try running %s", fmt.Sprintf("`%s core install %s`", globals.VersionInfo.Application, platformErr.Platform)))
```
See explanation above.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: cli/upload/upload.go (hunk 1 above)
Comment (cmaglie) [reply cli/upload/upload.go:139]: We may just always print `Try running './arduinoc-li core install arduino:samd'` and let the `core install` command print that the `Platform %s is not found in any known index` if appropriate.

Comment (silvanocerza) [reply cli/upload/upload.go:139]: I wouldn't do that, we're giving the user a solution that won't work. We're already know what's going to happen if she runs that, might has already say it.

**Comment by silvanocerza** [comment]
Link check workflows are failing again, it's a false positive as usual. Merging anyway. 

Thanks @per1234. <3
