### PR TITLE
Fix gRPC interface function to merge configs

### LINKED ISSUE #1161: [gRPC] Neither `merge` nor `setValue` can be used to unset a CLI config entry
### Current behavior

I can use neither `merge` nor `setValue` to unset a property in the CLI config when running in daemon mode.

Let assume I have the following state that is loaded by the `ArduinoCoreClient`, and I want to unset `proxy`.

```json
{
  "foo": "bar",
  "proxy": "http://blabla"
}
````

I tried to update the CLI state with the followings: 
```json
{ "network": { "proxy": undefined } }
```

```json
{ "network": { } }
```

Neither `merge` nor `setValue` worked.

### Expected behavior

I can unset a value.

### Environment

- CLI version (output of `arduino-cli version`): 0.15.0-rc1
- OS and platform:

### Additional context

This feature is required by https://github.com/arduino/arduino-pro-ide/issues/410

### PR DESCRIPTION
**Pull request by silvanocerza**
- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Bug fix.

- **What is the current behavior?**

Calling the gRPC interface Merge function to merge existing configs with new ones would ignored empty values.

* **What is the new behavior?**

This fix adds the possibility to set empty values with the Merge gRPC function, previously they would have been ignored.

Because of this change I had also to modify the GetValue() function since it would first check if the value was set using the Viper.InConfig() function that wouldn't check for values set with Viper.Set().

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

No.

* **Other information**:

Fixes #1161 

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

File: commands/daemon/settings.go [hunk 1]
```diff
@@ -40,15 +42,46 @@ func (s *SettingsService) GetAll(ctx context.Context, req *rpc.GetAllRequest) (*
...
+// For example:
+//    {"foo": "bar", "daemon":{"port":"420"}, "sketch": {"always_export_binaries": "true"}}
+// would convert to:
+//    {"foo": "bar", "daemon.port":"420", "sketch.always_export_binaries": "true"}
+func mapper(toMap map[string]interface{}) map[string]interface{} {
+	res := map[string]interface{}{}
+	for k, v := range toMap {
+		switch v.(type) {
+		case map[string]interface{}:
+			data := v.(map[string]interface{})
```
Comment (cmaglie) [inline commands/daemon/settings.go:55]:
```suggestion
		switch data := v.(type) {
		case map[string]interface{}:
```

File: commands/daemon/settings_test.go [hunk 2]
```diff
@@ -48,21 +48,68 @@ func TestGetAll(t *testing.T) {
...
+	require.Equal(t, "50051", configuration.Settings.GetString("daemon.port"))
+	require.Equal(t, "", configuration.Settings.GetString("foo"))
+	require.Equal(t, false, configuration.Settings.GetBool("sketch.always_export_binaries"))
+
+	bulkSettings = `{"daemon": {"port":""}}`
+	res, err = svc.Merge(context.Background(), &rpc.RawData{JsonData: bulkSettings})
+	require.NotNil(t, res)
+	require.NoError(t, err)
+
+	require.Equal(t, "", configuration.Settings.GetString("daemon.port"))
```
Comment (cmaglie) [inline commands/daemon/settings_test.go:80]:
```suggestion
	require.Equal(t, "", configuration.Settings.GetString("foo"))
	require.Equal(t, false, configuration.Settings.GetBool("sketch.always_export_binaries"))
```

**Review by cmaglie — APPROVED** [review]
I've added some suggestions, overall LGTM :+1:
