### PR TITLE
Fix lib upgrade command not installing new libraries dependencies

### LINKED ISSUE #1856: `lib upgrade` does not install dependencies
### Describe the problem

Arduino libraries may have dependencies on other libraries. These can be specified in the [library's metadata](https://arduino.github.io/arduino-cli/dev/library-specification/#library-metadata), which will cause Arduino CLI to install them along with the library.

🐛 The dependencies of a library are not installed when a new version of the dependent library is installed by `arduino-cli lib upgrade`

### To reproduce

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 05d14464 Date: 2022-08-30T19:43:20Z

$ arduino-cli lib uninstall MKRWAN
Uninstalling MKRWAN@1.1.0...

$ arduino-cli lib install Arduino_ConnectionHandler@0.3.3
Already installed MKRGSM@1.5.0
Already installed MKRNB@1.5.1
Already installed Arduino_DebugUtils@1.3.0
Already installed WiFi101@0.16.1
Already installed WiFiNINA@1.8.13
Downloading Arduino_ConnectionHandler@0.3.3...
Arduino_ConnectionHandler@0.3.3 already downloaded
Installing Arduino_ConnectionHandler@0.3.3...
Installed Arduino_ConnectionHandler@0.3.3

$ arduino-cli lib deps Arduino_ConnectionHandler@0.3.3
✓ MKRNB 1.5.1 is already installed.
✓ Arduino_ConnectionHandler 0.3.3 is already installed.
✓ Arduino_DebugUtils 1.3.0 is already installed.
✓ WiFi101 0.16.1 is already installed.
✓ WiFiNINA 1.8.13 is already installed.
✓ MKRGSM 1.5.0 is already installed.

$ arduino-cli lib upgrade
Downloading Arduino_ConnectionHandler@0.6.6...
Arduino_ConnectionHandler@0.6.6 already downloaded
Installing Arduino_ConnectionHandler@0.6.6...
Replacing Arduino_ConnectionHandler@0.3.3 with Arduino_ConnectionHandler@0.6.6...
Installed Arduino_ConnectionHandler@0.6.6

$ arduino-cli lib deps Arduino_ConnectionHandler@0.6.6
✓ WiFiNINA 1.8.13 is already installed.
✓ MKRGSM 1.5.0 is already installed.
✓ MKRNB 1.5.1 is already installed.
✕ MKRWAN 1.1.0 must be installed.
✓ Arduino_ConnectionHandler 0.6.6 is already installed.
✓ Arduino_DebugUtils 1.3.0 is already installed.
✓ WiFi101 0.16.1 is already installed.
```

🐛 The new dependency `MKRWAN` (added after the time of the `Arduino_ConnectionHandler@0.3.3` release) was not installed.

### Expected behavior

Install dependencies of libraries upgraded by `arduino-cli lib upgrade`, just as already happens when upgrading individual libraries (e.g., `arduino-cli lib install Arduino_ConnectionHandler`).

### Arduino CLI version

05d14464

### Operating system

Windows

### Operating system version

Windows 10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by silvanocerza**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?

Bug fix on an existing command.

## What is the current behavior?

Current behaviour is explained in issue #1856

## What is the new behavior?

Calling `lib upgrade` now will also install newly added dependencies to libraries being updated. 
This fixes also the gRPC interface commands `LibraryUpgradeAll` and `LibraryUpgrade`.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

Nope.

## Other information

Fixes #1856.

This PR depends on #1934.

### CODE REVIEW

File: internal/integrationtest/lib/lib_test.go [hunk 1]
```diff
@@ -136,3 +137,83 @@ func TestDuplicateLibInstallDetection(t *testing.T) {
...
+	require.NoError(t, err)
+	lines := strings.Split(strings.TrimSpace(string(stdOut)), "\n")
+	require.Len(t, lines, 7)
+	require.Equal(t, "✓ Arduino_DebugUtils 1.3.0 is already installed.", lines[0])
+	require.Equal(t, "✓ MKRGSM 1.5.0 is already installed.", lines[1])
+	require.Equal(t, "✓ MKRNB 1.5.1 is already installed.", lines[2])
+	require.Equal(t, "✓ WiFiNINA 1.8.13 is already installed.", lines[3])
+	require.Equal(t, "✕ Arduino_ConnectionHandler 0.6.6 must be installed.", lines[4])
+	require.Equal(t, "✕ MKRWAN 1.1.0 must be installed.", lines[5])
+	require.Equal(t, "✕ WiFi101 0.16.1 must be installed.", lines[6])
```
Comment (cmaglie) [inline internal/integrationtest/lib/lib_test.go:171]: These tests will fail as soon as these libraries get new releases, we should exclude the current latest version from the checks (or maybe just check the JSON output only)

**Review by cmaglie — CHANGES_REQUESTED** [review]
Nice idea to call `LibraryInstall` internally.

File: cli/lib/check_deps.go [hunk 2]
```diff
@@ -81,13 +82,27 @@ func (dr checkDepResult) Data() interface{} {
...
+	})
+
+	for _, dep := range deps {
 		res += outputDep(dep)
 	}
 	return res
 }
 
 func outputDep(dep *rpc.LibraryDependencyStatus) string {
+
```
Comment (cmaglie) [inline cli/lib/check_deps.go:105]:
```suggestion
```

**Review by cmaglie — APPROVED** [review]
