### PR TITLE
Fix resolution of library names when checking for upgrades

### LINKED ISSUE #1041: Newer library is not listed as available
### Current behavior

```
alranel@MacBook-Pro libraries % arduino-cli lib update-index
Updating index: library_index.json downloaded
alranel@MacBook-Pro libraries % arduino-cli lib list
Name                               Installed Available Location Description
Adafruit-PN532-master              1.0.2 -       user     Arduino library for SPI and I2C acces...
Adafruit_BusIO                     1.3.3 -       user     This is a library for abstracting awa...
Adafruit_Circuit_Playground        1.10.4 -       user     All in one library to control Adafrui...
Adafruit_DotStar                   1.1.4 -       user     Adafruit DotStar LED Library
Adafruit_GFX_Library               1.9.0 -       user     Adafruit GFX graphics core library, t...
Adafruit_seesaw_Library            1.3.1 -       user     This is a library for the Adafruit se...
Adafruit_ST7735_and_ST7789_Library 1.5.18 -       user     This is a library for the Adafruit ST...
Arduino_APDS9960                   1.0.3 -       user     A library for the APDS9960 sensor
Arduino_BQ24195                    0.9.0 -       user     Arduino library for the BQ24195 Power...
Arduino_HTS221                     1.0.0 -       user     Allows you to read the temperature an...
Arduino_LPS22HB                    1.0.0 -       user     Allows you to read the pressure senso...
Arduino_LSM6DS3                    1.0.0 -       user     Allows you to read the accelerometer ...
Arduino_MCHPTouch                  1.0.0 -       user     A library for the Atmel touch sensors
Arduino_MicroPython                1.0.0 -       user     MicroPython for Arduino
Arduino_MKRENV                     1.1.0 -       user     Allows you to read the temperature, h...
Arduino_MKRIoTCarrier              0.9.4 -       user     Controlling the IoT MKR Carrier
ArduinoBLE                         1.1.2 1.1.3   user     Enables BLE connectivity on the Ardui...
cie-PN532-master                   1.0.0 -       user     Arduino library for SPI access to the...
MAX77650-Arduino-Library           1.0.1 -       user     An Arduino library for the Maxim Powe...
SD                                 1.2.4 -       user     Enables reading and writing on SD cards.
Servo                              1.1.6 1.1.7   user     Allows Arduino/Genuino boards to cont...
SpacebrewYun                       1.0.2 -       user     Enables the communication between int...
WiFiNINA                           1.7.1 -       user     Enables network connection (local and...
```

The installed version of `Adafruit_ST7735_and_ST7789_Library` is 1.5.18 and no newer version is listed under "Available".

### Expected behavior

As of now, the library index contains the version 1.6.0 of `Adafruit ST7735 and ST7789 Library`, so I would expect it to be listed.

This is correctly reflected in the IDE:

Screenshot 2020-10-20 at 12 49 11

### Environment

- CLI version (output of `arduino-cli version`): 0.13.0 Commit: 693a045eea420c29ca7027e668eee31bce37365d
- OS and platform: macOS 10.15.4

### PR DESCRIPTION
**Pull request by stonehippo**
**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

This change resolves #1041, where packages that have upgrades based on `library_index.json` do not show up as upgradable with using the `arduino-cli lib` commands.

- **What is the current behavior?**

When using the `arduino-cli lib` commands to check for or apply updates, packages that have spaces in the name in the index are not shown as upgradable.

* **What is the new behavior?**

The overall behavior is unchanged and commands remain as currently implemented and documented. However, the resolution of packages that have spaces in the names now works, so commands such as `arduino-cli lib list --updatable` will now show all upgradable packages.

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

No

* **Other information**:

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

### CODE REVIEW

File: arduino/libraries/librariesindex/index.go [hunk 1]
```diff
@@ -125,7 +126,8 @@ func (idx *Index) FindRelease(ref *Reference) *Release {
 // FindIndexedLibrary search an indexed library that matches the provided
 // installed library or nil if not found
 func (idx *Index) FindIndexedLibrary(lib *libraries.Library) *Library {
-	return idx.Libraries[lib.Name]
+	clean := strings.ReplaceAll(lib.Name, "_", " ")
```
Comment (per1234) [inline arduino/libraries/librariesindex/index.go:129]: Thanks for your pull request @stonehippo

Unfortunately this proposal will only transfer the bug from one format of library name to another. Consider what happens to the libraries with an underscore in their name:

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 9f050282 Date: 2022-05-08T06:18:23Z

$ arduino-cli lib search Arduino_MKRENV
Downloading index: library_index.json.gz downloaded
Downloading index signature: library_index.json.sig downloaded
Name: "Arduino_MKRENV"
  Author: Arduino
  Maintainer: Arduino <info@arduino.cc>
  Sentence: Allows you to read the temperature, humidity, pressure, light and UV sensors of your MKR ENV Shield.
  Paragraph:
  Website: http://github.com/arduino-libraries/Arduino_MKRENV
  Category: Sensors
  Architecture: samd
  Types: Arduino
  Versions: [1.0.0, 1.1.0, 1.2.0, 1.2.1]
  Provides includes: Arduino_MKRENV.h

$ arduino-cli lib install Arduino_MKRENV@1.2.0
Downloading Arduino_MKRENV@1.2.0...
Arduino_MKRENV@1.2.0 downloaded
Installing Arduino_MKRENV@1.2.0...
Installed Arduino_MKRENV@1.2.0

$ arduino-cli lib list --updatable
No updates available.
```

The solution is to fix the root bug rather than trying to put a bandaid over it. Every library has a canonical name and the library must always be referred to by this name:

- If the library has [a `library.properties` metadata file](https://arduino.github.io/arduino-cli/dev/library-specification/#libraryproperties-file-format) (["1.5 format"](https://arduino.github.io/arduino-cli/dev/library-specification/#15-library-format-rev-22)), the library name is defined by the `name` field of `library.properties`.
- If the library does not have a `library.properties` metadata file (["1.0" or "legacy" format](https://arduino.github.io/arduino-cli/dev/library-specification/#old-library-format-pre-15)), the library name is defined by the folder name the library is installed in.

The bug is that some parts of Arduino CLI are using the library folder name as the library name even for "1.5 format" libraries, as is tracked here: https://github.com/arduino/arduino-cli/issues/932. That is the bug that must be fixed. https://github.com/arduino/arduino-cli/issues/1041 is only a symptom of https://github.com/arduino/arduino-cli/issues/932

**Review by per1234 — CHANGES_REQUESTED** [review]

File: arduino/libraries/librariesindex/index.go (hunk 1 above)
Comment (stonehippo) [reply arduino/libraries/librariesindex/index.go:129]: @per1234 fair point. Of course, based on the current library_index.json, the existing implementation harms more than the fix (about twice as many libs have spaces in the name as underscores). ;-)

I'm going to kill this, and go see if I can fix #932, since the lib upgrade function is less than ideal if more than 25% of the libraries get missed (1322 of the total 4828 libraries in the index have spaces in the name field that the CLI currently relies on; 776 contain spaces).

Comment (stonehippo) [reply arduino/libraries/librariesindex/index.go]: @per1234 

After taking another look at #932, I've pushed a change to this PR. Rather than replacing the underscores in the installed name, it uses the `RealName` of the lib for upgrade lookups. If a library does not have a `library.properties` file, it is still listed, but cannot be upgraded via the `arduino-cli lib upgrade` command, since the index is currently relied upon find the latest version.

It might make sense to mark those libraries as "legacy" to declare that they have to be upgraded manually (or via the `install` command, if they're in the index but still not conforming to the 1.5 spec).

Note that the `uninstall` command uses a different resolving mechanism and will uninstall libraries based on their real names or directory names. It may also make sense to use this resolving mechanism in place of what I have here, but I'll leave that to reviewers to weigh in on.

Comment (stonehippo) [reply arduino/libraries/librariesindex/index.go]: @per1234 ok, I noticed the tests I (somewhere stupidly) broke and fixed them. This is ready for review again when you have a moment.

**Comment by per1234** [comment]
>It might make sense to mark those libraries as "legacy" to declare that they have to be upgraded manually

They are already marked as such in the `[*].library.is_legacy` field of the machine readable output:

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: d4d1fa91 Date: 2022-05-10T02:50:00Z

$ export ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL="true"

$ arduino-cli lib install --git-url https://github.com/arduino/HMC5983
--git-url and --zip-path flags allow installing untrusted files, use it at your own risk.
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Compressing objects: 100% (7/7), done.
Total 9 (delta 0), reused 6 (delta 0), pack-reused 0
Library installed

$ arduino-cli lib list --format json
[
  {
    "library": {
      "name": "HMC5983",
      "architectures": [
        "*"
      ],
      "install_dir": "E:\\deleteme\\arduino-cli\\directories\\user\\libraries\\HMC5983",
      "source_dir": "e:\\deleteme\\arduino-cli\\directories\\user\\libraries\\HMC5983",
      "is_legacy": true,
      "location": 1,
      "examples": [
        "E:\\deleteme\\arduino-cli\\directories\\user\\libraries\\HMC5983\\examples\\single_read"
      ],
      "provides_includes": [
        "HMC5983.h"
      ]
    }
  }
]
```

Of course the average user will be using the `text` format output, but I'm not sure how much of a concern it is in reality since the libraries using that ancient format are not very common these days and when they are used it is likely no update will become available.

>if they're in the index but still not conforming to the 1.5 spec

1.5 format is [a requirement](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager) for inclusion in the index, so there are no "legacy" format libraries in the index.

>Note that the uninstall command uses a different resolving mechanism and will uninstall libraries based on their real names or directory names. It may also make sense to use this resolving mechanism in place of what I have here, but I'll leave that to reviewers to weigh in on.

Thanks for pointing that out. I am against it. In my opinion, there should be one and only one name for each library, which is always used when referring to the library in the Arduino CLI output and in the commands. So I think the way you chose to make `lib upgrade` work here is correct.

**Review by per1234 — APPROVED** [review]
Thanks @stonehippo!

This PR fixes only one of several of the symptoms of an unintuitive and flawed approach to handling names of installed libraries. However, it does indeed fix that symptom and thus is a valuable contribution by making the behavior of Arduino CLI less buggy in this respect.

So I am in support of merging this, even though the big picture is that the entire local library name system needs to be reworked from the root of the problem in the design of [`github.com/arduino/arduino-cli/arduino/libraries.Library`](https://github.com/arduino/arduino-cli/blob/65f662a782780f9e410a3c327b213e55163f4de9/arduino/libraries/libraries.go#L53) on up.

I'll give a little time in case other maintainers want to review before merging.

**Comment by stonehippo** [comment]
Thanks, @per1234. I agree re the current system. It's really hard to make definitive calls about the state of a user's installed libraries vs the index. You're right that this is only a patch over the symptoms, but it's going to take some collective work to reconcile the deeper issue.
