### PR TITLE
[skip-changelog] Remove empty object from the output of grpc commands

### LINKED ISSUE #2046: grpc empty object when updating the library index
### Describe the problem

When using an grpclient to update the library index, command `UpdateLibrariesIndex`, the download process is ended by and empty object following the "end" message

### To reproduce

Start the CLI in deamon mode
```
arduino-cli daemon
```
Create an instance (here using the `grpcurl` tool)
```shell
grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Create
```
Issue an  `UpdateLibrariesIndex` command
```shell
grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.UpdateLibrariesIndex
 ```
 You should observe an output similar to the following
 ```json
{
  "downloadProgress": {
    "start": {
      "url": "https://downloads.arduino.cc/libraries/library_index.tar.bz2",
      "label": "Downloading index: library_index.tar.bz2"
    }
  }
}
{
  "downloadProgress": {
    "update": {
      "downloaded": "2358123",
      "totalSize": "2358123"
    }
  }
}
{
  "downloadProgress": {
    "end": {
      "success": true
    }
  }
}
{

}
 ```
 Notice how there's an empty `{}` object at the bottom

### Expected behavior

The message
```json
{
  "downloadProgress": {
    "end": {
      "success": true
    }
  }
}
```
Closes the stream with no additional objects

### Arduino CLI version

commit a58d5ad

### Operating system

macOS

### Operating system version

13.1 (22C65)

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the problem still occurs when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My report contains all necessary details

### PR DESCRIPTION
**Pull request by MatteoPologruto**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?
gRPC code imperfection fix

## What is the current behavior?
Some gRPC commands like `UpdateLibrariesIndex` stream an empty object after a successful execution.

## What is the new behavior?
The empty object has been removed.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?
No

Close #2046

### CODE REVIEW

File: commands/daemon/daemon.go [hunk 1]
```diff
@@ -357,10 +354,7 @@ func (s *ArduinoCoreServerImpl) LibraryInstall(req *rpc.LibraryInstallRequest, s
 		func(p *rpc.DownloadProgress) { stream.Send(&rpc.LibraryInstallResponse{Progress: p}) },
 		func(p *rpc.TaskProgress) { stream.Send(&rpc.LibraryInstallResponse{TaskProgress: p}) },
 	)
-	if err != nil {
-		return convertErrorToRPCStatus(err)
-	}
-	return stream.Send(&rpc.LibraryInstallResponse{})
+	return convertErrorToRPCStatus(err)
```
Comment (Bikappa) [inline commands/daemon/daemon.go:357]: Can a similar approach be applied to other `stream.Send()`? Like the return at the end of the `PlatformInstall` command above.
Also I think we should also add some test to avoid regression
