### PR TITLE
Fix core upgrade

### LINKED ISSUE #285: Uninstall does not remove lib binaries
## Bug Report
Lib uninstall should not only remove libs from the index but also remove the corresponding binary in .arduino15/staging/libraries/ or at least have an option to avoid removing the lib binary. Default behaviour should be to remove the bin too.

### Current behavior
```
$ arduino-cli lib install 'WiFiNINA'
Downloading WiFiNINA@1.4.0...
WiFiNINA@1.4.0 already downloaded
Installing WiFiNINA@1.4.0...
Installed WiFiNINA@1.4.0
$ arduino-cli lib uninstall 'WiFiNINA'
Uninstalling WiFiNINA@1.4.0...
$ ls -l ~/.arduino15/staging/libraries/
total 232
-rw-r--r-- 1 luca luca  83192 Jul 15 14:49 WiFiNINA-1.4.0.zip
$ arduino-cli lib download 'WiFiNINA'
WiFiNINA@1.4.0 already downloaded
```

### Expected behavior
Uninstall should remove the lib file

### Environment

- CLI version (output of `arduino-cli version`): arduino-cli Version: 0.3.7-alpha.preview Commit:  BuildDate: 2019-07-17 10:37:06.0191213 +0000 UTC
- Go version (if building from sources): 1.12
- OS version: Windows 10, Windows WSL

### PR DESCRIPTION
**Pull request by masci**
This PR fixes the case where no args are passed to the upgrade command, like:
```
arduino-cli core upgrade
```
Now an upgrade will be performed to any core that is up to date. If all the cores are at the latest version, command is a no op and will exit without errors, providing and info message.

Fixes ~#285~ #273  

## Additional notes

I took the opportunity to review the design of the code that lists all the available cores that was depending on the `rpc` package for no reason. Also the api of the old `PlatformList` required a `context` that was never used.

Other minor improvements are commented inline.

### CODE REVIEW

File: arduino/cores/status.go [hunk 1]
```diff
@@ -59,22 +55,46 @@ func (packages *Packages) GetOrCreatePackage(packager string) *Package {
...
+	for n := range packages {
 		res[i] = n
 		i++
 	}
 	sortutil.CiAsc(res)
 	return res
 }
 
+// GetDepsOfPlatformRelease returns the deps of a specified release of a core.
+func (packages Packages) GetDepsOfPlatformRelease(release *PlatformRelease) ([]*ToolRelease, error) {
```
Comment (masci) [inline arduino/cores/status.go]: this was just moved up in the source module

File: arduino/cores/status.go [hunk 2]
```diff
@@ -25,15 +25,11 @@ import (
 )
 
 // Packages represents a set of Packages
-type Packages struct {
-	Packages map[string]*Package // Maps packager name to Package
-}
+type Packages map[string]*Package // Maps packager name to Package
```
Comment (masci) [inline arduino/cores/status.go]: no reason for this indirection level that also makes the use of the map awkward by having to repeat `packages.Packages`

File: arduino/cores/status.go [hunk 3]
```diff
@@ -44,13 +40,13 @@ type Package struct {
 	Email      string               // Email of maintainer.
 	Platforms  map[string]*Platform // The platforms in the system.
 	Tools      map[string]*Tool     // The tools in the system.
-	Packages   *Packages            `json:"-"`
```
Comment (masci) [inline arduino/cores/status.go]: now that `Packages` is aliased to a map, no need to send around a pointer, map is already a reference

File: arduino/cores/status.go [hunk 4]
```diff
@@ -132,27 +152,3 @@ func (tdep ToolDependency) extractRelease(sc Packages) (*ToolRelease, error) {
 	}
 	return release, nil
 }
-
-// GetDepsOfPlatformRelease returns the deps of a specified release of a core.
-func (packages *Packages) GetDepsOfPlatformRelease(release *PlatformRelease) ([]*ToolRelease, error) {
```
Comment (masci) [inline arduino/cores/status.go]: see previous comment, this was just moved

File: commands/core/upgrade.go [hunk 5]
```diff
@@ -71,7 +77,7 @@ func upgradePlatform(pm *packagemanager.PackageManager, platformRef *packagemana
 	}
 	latest := platform.GetLatestRelease()
 	if !latest.Version.GreaterThan(installed.Version) {
-		return fmt.Errorf("platform %s is already at the latest version", platformRef)
+		return ErrAlreadyLatest
```
Comment (masci) [inline commands/core/upgrade.go]: this way we avoid returning an error if users ask to upgrade a core that's already latest

File: commands/daemon/daemon.go [hunk 6]
```diff
@@ -194,7 +194,19 @@ func (s *ArduinoCoreServerImpl) PlatformSearch(ctx context.Context, req *rpc.Pla
...
+	if err != nil {
+		return nil, err
+	}
+
+	installed := []*rpc.Platform{}
+	for _, p := range platforms {
+		rpcPlatform := core.PlatformReleaseToRPC(p)
+		rpcPlatform.Installed = p.Version.String()
+		installed = append(installed, rpcPlatform)
+	}
```
Comment (masci) [inline commands/daemon/daemon.go]: this code was moved here from the `core` package since here it's legit to depend on `rpc`

File: arduino/cores/packagemanager/package_manager.go [hunk 7]
```diff
@@ -51,28 +50,18 @@ type PackageManager struct {
...
+		Packages:    cores.NewPackages(),
 		IndexDir:    indexDir,
 		PackagesDir: packagesDir,
 		DownloadDir: downloadDir,
 		TempDir:     tempDir,
 	}
 }
 
-// Clear FIXMEDOC
-func (pm *PackageManager) Clear() {
```
Comment (masci) [inline arduino/cores/packagemanager/package_manager.go]: this wasn't used anywhere

**Comment by mastrolinux** [comment]
Affected by the same issue as libs

```
$ ./arduino-cli core install arduino:samd@1.8.2
Downloading packages...
arduino:arm-none-eabi-gcc@7-2017q4 already downloaded
arduino:bossac@1.7.0-arduino3 already downloaded
arduino:openocd@0.10.0-arduino7 already downloaded
arduino:CMSIS@4.5.0 already downloaded
arduino:CMSIS-Atmel@1.2.0 already downloaded
arduino:arduinoOTA@1.2.1 already downloaded
arduino:samd@1.8.2 already downloaded
Installing arduino:arm-none-eabi-gcc@7-2017q4...
arduino:arm-none-eabi-gcc@7-2017q4 installed
Installing arduino:bossac@1.7.0-arduino3...
arduino:bossac@1.7.0-arduino3 installed
Installing arduino:openocd@0.10.0-arduino7...
arduino:openocd@0.10.0-arduino7 installed
Installing arduino:CMSIS@4.5.0...
arduino:CMSIS@4.5.0 installed
Installing arduino:CMSIS-Atmel@1.2.0...
arduino:CMSIS-Atmel@1.2.0 installed
Installing arduino:arduinoOTA@1.2.1...
arduino:arduinoOTA@1.2.1 installed
Installing arduino:samd@1.8.2...
arduino:samd@1.8.2 installed


$ ls -l ~/.arduino15/staging/packages/
total 198192
-rw-r--r-- 1 luca luca  1974030 Apr 18 18:23 arduinoOTA-1.2.0-linux_amd64.tar.bz2
-rw-r--r-- 1 luca luca  2257689 Jul 18 16:31 arduinoOTA-1.2.1-linux_amd64.tar.bz2
-rw-r--r-- 1 luca luca   207271 Jul 18 16:31 bossac-1.7.0-arduino3-linux64.tar.gz
-rw-r--r-- 1 luca luca    31373 Apr 18 18:25 bossac-1.7.0-x86_64-linux-gnu.tar.gz
-rw-r--r-- 1 luca luca 31525196 Apr 18 17:30 CMSIS-4.5.0.tar.bz2
-rw-r--r-- 1 luca luca  1659108 Apr 18 17:30 CMSIS-Atmel-1.1.0.tar.bz2
-rw-r--r-- 1 luca luca  2221805 Jul 18 16:31 CMSIS-Atmel-1.2.0.tar.bz2
-rw-r--r-- 1 luca luca 51395093 Apr 18 17:53 gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
-rw-r--r-- 1 luca luca 99857645 Jul 18 16:31 gcc-arm-none-eabi-7-2017-q4-major-linux64.tar.bz2
-rw-r--r-- 1 luca luca  1701581 Jul 18 16:31 openocd-0.10.0-arduino7-static-x86_64-ubuntu12.04-linux-gnu.tar.bz2
-rw-r--r-- 1 luca luca  1394293 Apr 18 18:26 openocd-0.9.0-arduino6-static-x86_64-linux-gnu.tar.bz2
-rw-r--r-- 1 luca luca  2848675 Apr 18 17:51 samd-1.6.21.tar.bz2
-rw-r--r-- 1 luca luca  2894202 Jul 19 10:43 samd-1.8.2.tar.bz2
-rw-r--r-- 1 luca luca  2897712 Jul 18 16:31 samd-1.8.3.tar.bz2


$ ./arduino-cli core uninstall arduino:samd
Uninstalling arduino:samd@1.8.2...
arduino:samd@1.8.2 uninstalled
Uninstalling arduino:arm-none-eabi-gcc@7-2017q4, tool is no more required...
arduino:arm-none-eabi-gcc@7-2017q4 uninstalled
Uninstalling arduino:bossac@1.7.0-arduino3, tool is no more required...
arduino:bossac@1.7.0-arduino3 uninstalled
Uninstalling arduino:openocd@0.10.0-arduino7, tool is no more required...
arduino:openocd@0.10.0-arduino7 uninstalled
Uninstalling arduino:CMSIS@4.5.0, tool is no more required...
arduino:CMSIS@4.5.0 uninstalled
Uninstalling arduino:CMSIS-Atmel@1.2.0, tool is no more required...
arduino:CMSIS-Atmel@1.2.0 uninstalled
Uninstalling arduino:arduinoOTA@1.2.1, tool is no more required...
arduino:arduinoOTA@1.2.1 uninstalled

$ ls -l ~/.arduino15/staging/packages/
total 198192
-rw-r--r-- 1 luca luca  1974030 Apr 18 18:23 arduinoOTA-1.2.0-linux_amd64.tar.bz2
-rw-r--r-- 1 luca luca  2257689 Jul 18 16:31 arduinoOTA-1.2.1-linux_amd64.tar.bz2
-rw-r--r-- 1 luca luca   207271 Jul 18 16:31 bossac-1.7.0-arduino3-linux64.tar.gz
-rw-r--r-- 1 luca luca    31373 Apr 18 18:25 bossac-1.7.0-x86_64-linux-gnu.tar.gz
-rw-r--r-- 1 luca luca 31525196 Apr 18 17:30 CMSIS-4.5.0.tar.bz2
-rw-r--r-- 1 luca luca  1659108 Apr 18 17:30 CMSIS-Atmel-1.1.0.tar.bz2
-rw-r--r-- 1 luca luca  2221805 Jul 18 16:31 CMSIS-Atmel-1.2.0.tar.bz2
-rw-r--r-- 1 luca luca 51395093 Apr 18 17:53 gcc-arm-none-eabi-4.8.3-2014q1-linux64.tar.gz
-rw-r--r-- 1 luca luca 99857645 Jul 18 16:31 gcc-arm-none-eabi-7-2017-q4-major-linux64.tar.bz2
-rw-r--r-- 1 luca luca  1701581 Jul 18 16:31 openocd-0.10.0-arduino7-static-x86_64-ubuntu12.04-linux-gnu.tar.bz2
-rw-r--r-- 1 luca luca  1394293 Apr 18 18:26 openocd-0.9.0-arduino6-static-x86_64-linux-gnu.tar.bz2
-rw-r--r-- 1 luca luca  2848675 Apr 18 17:51 samd-1.6.21.tar.bz2
-rw-r--r-- 1 luca luca  2894202 Jul 19 10:43 samd-1.8.2.tar.bz2
-rw-r--r-- 1 luca luca  2897712 Jul 18 16:31 samd-1.8.3.tar.bz2
```

does not solve https://github.com/arduino/arduino-cli/issues/285 either. Everything else LGTM

**Comment by masci** [comment]
@mastrolinux my bad, I copypasted the wrong issue number, this is actually for #273 I've fixed PR description

**Comment by mastrolinux** [comment]
I can confirm that is fixed and I am going to prepare an integration test for it.
