### PR TITLE
fix: redirect postinstall script output to runtime output

### LINKED ISSUE #1675: Output from post install script is not printed
## Describe the bug

Arduino boards platform authors may add a ["post-install script"](https://arduino.github.io/arduino-cli/dev/platform-specification/#post-install-script) to their platform. Arduino CLI and Arduino IDE run this script at the end of the platform installation process.

🐛 Output from the script is not printed. This output might provide instructions to the user or information useful for troubleshooting an error during the script execution.

## To Reproduce

```text
$ arduino-cli version
arduino-cli  Version: nightly-20220224 Commit: 2f2cbe2 Date: 2022-02-24T01:31:21Z

$ arduino-cli core uninstall arduino:mbed_nano
Uninstalling arduino:mbed_nano@2.7.2...
Platform arduino:mbed_nano@2.7.2 uninstalled

$ arduino-cli core install arduino:mbed_nano@2.7.2
Tool arduino:openocd@0.11.0-arduino2 already installed
Tool arduino:arm-none-eabi-gcc@7-2017q4 already installed
Tool arduino:bossac@1.9.1-arduino2 already installed
Tool arduino:dfu-util@0.10.0-arduino1 already installed
Tool arduino:rp2040tools@1.0.2 already installed
Downloading packages...
arduino:mbed_nano@2.7.2 already downloaded
Installing platform arduino:mbed_nano@2.7.2...
Configuring platform....
Platform arduino:mbed_nano@2.7.2 installed
```

The process was not run as root, so it was necessary for the script to exit without configuring the udev rules as intended:

https://github.com/arduino/ArduinoCore-mbed/blob/2.7.2/post_install.sh#L12-L15

```sh
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
```

🐛 The Arduino CLI output does not include the script output:

```text
Please run as root
```

## Expected behavior

Arduino CLI prints any output from the post-install script, as is done by Arduino IDE 1.x.

## Desktop

- OS: Ubuntu 20.04
- nightly-20220224 Commit: 2f2cbe2 Date: 2022-02-24T01:31:21Z

## Additional context

I realize that it is very questionable whether the output from the particular script used by the demo is of any value. But that only indicates a defect in the implementation of this specific script, not that script output is fundamentally worthless.

### Related

- https://github.com/arduino/arduino-cli/pull/893
- https://github.com/arduino/ArduinoCore-mbed/issues/231

### PR DESCRIPTION
**Pull request by Bikappa**
## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

Pipe the forked post install script logs into the parent process (the cli) logs

## What is the current behavior?

Post install script logs are not visible when installing a core

## What is the new behavior?

stdout and stderr streams of the post install script are shown in the cli stdout and stderr respectively

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No, users should not expect to have structured logs from the cli 

## Other information

Fixes  #1675

### CODE REVIEW

File: arduino/cores/packagemanager/install_uninstall.go [hunk 1]
```diff
@@ -237,6 +238,9 @@ func (pme *Explorer) RunPostInstallScript(installDir *paths.Path) error {
 		if err != nil {
 			return err
 		}
+		cmd.RedirectStdoutTo(os.Stdout)
+		cmd.RedirectStderrTo(os.Stderr)
```
Comment (cmaglie) [inline arduino/cores/packagemanager/install_uninstall.go:242]: I fear that is more complicated than this... this breaks the JSON output, and we must use the `feedback` package to avoid that.

Probably the most simple way is to pass two `io.Writers` to `RunPostInstallScript`:

```go
func (pme *Explorer) RunPostInstallScript(installDir *paths.Path, stdout, stderr io.Writer) error {
```

and redirect the output to those streams. Also, this is a breaking API change in golang to document in UPGRADING.md

**Review by cmaglie — CHANGES_REQUESTED** [review]

File: arduino/cores/packagemanager/install_uninstall.go (hunk 1 above)
Comment (Bikappa) [reply arduino/cores/packagemanager/install_uninstall.go:242]: I see thanks for noticing. Let me check what writers would fit

**Review by cmaglie — APPROVED** [review]
Code LGTM, let's wait for a test on the IDE by @ubidefeo :-)

**Review by ubidefeo — COMMENTED** [review]
Functionally sound.
I reported that while the `Please run as root` message is displayed to the user, 
the installation is reported as finished, hence successful.
```bash
$> arduino-cli core install arduino:mbed_nano
Configuring platform....
Please run as root
...
Platform arduino:mbed_nano@4.0.2 installed
$> 
```

Running 
```bash
$> sudo arduino-cli core install arduino:mbed_nano
Platform arduino:mbed_nano@4.0.2 already installed
```

Will fail to reinstall the platform and run the post-install required installers.
This forces the user to `uninstall` and then `sudo` to install the platform again.

Platforms should receive an update to the script to trigger an exit code `!=0` in case not invoked as `root`

cc @cmaglie @per1234 @facchinm

**Comment by cmaglie** [comment]
@ubidefeo I asked you to test on the **IDE**, we already tested the `arduino-cli` via command-line and it works fine AFAICT.

> This forces the user to uninstall and then sudo to install the platform again.

This may be a practical procedure for the CLI, but I don't think the users from the IDE will be happy to run the whole IDE as root...
Also `Not run as root` is just one of the 1623 possible things that can go wrong.

> Platforms should receive an update to the script to trigger an exit code !=0 in case not invoked as root

If your proposal is to un-do the installation (remove all the platforms/tools just installed) if the post-install script fails, then this is a much more involved change than the one proposed here.

**Comment by cmaglie** [comment]
Another idea could be to print something like:
```
WARNING: The configuration script returned an error (code 1):

  Not run as root

The platform is installed, but it may require the installation of drivers
or other manual intervention to work properly.
```

**Comment by Bikappa** [comment]
@cmaglie @ubidefeo I'd close this one if it's ok with you. Making the script fail and handling the failure is a different topic than showing its output.
For completeness, currently when the script fails (which is not the case for the example one in the issue), the following warning is shown:
```
Please run as root

WARNING cannot configure platform: exit status 1
Platform arduino:mbed_nano@2.7.2 installed
```
(I modified it here to make it exit with `1`)
