### PR TITLE
[breaking] `core update-index` do not stop at the first download error

### LINKED ISSUE #1788: [gRPC] It should be possible to run the `core update-index` equivalent with and without the 3rd party URLs
### Describe the request

As described in arduino/arduino-cli#1762, the `core update-index` gRPC equivalent must run before initializing the core gRPC client (`InitRequest`) if it's the first start:

> first start, and the core and lib indexes must be updated before running the init phase of the gRCP core client

This is doable, however, if there is a CLI config with an invalid 3rd URL (see https://github.com/arduino/arduino-ide/issues/1084), then the entire `core update-index` command will fail and makes the core gRPC client non-functional.

```
Error: 13 INTERNAL: Error downloading index 'https://downloads.arduino.cc/packages/package_nonexistent_index.json': Server responded with: 404 Not Found
```

### Describe the current behavior

As a consumer of the CLI APIs, I want to run the `core update-index` so that it only downloads the essential package index (`#directories.data/package_index.json`) and the built-in tools (`builtin:serial-discovery` and `builtin:mdns-discovery`). I also want to run the `core update-index` when it pulls all the package indexes required for the 3rd party platforms. A boolean flag on the gRPC API would be great to achieve it!

### Arduino CLI version

From the `HEAD`: `arduino-cli  Version: 0.0.0-git Commit:  Date:`

### Operating system

macOS

### Operating system version

12.3.1

### Additional context

_No response_

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details

### PR DESCRIPTION
**Pull request by cmaglie**
**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)
- [X] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**
  1. The `core update-index` do not stop anymore at the first error
  2. The `UpdateIndex` gRPC call has a new flag `ignore_custom_package_indexes` to allow skipping the update of custom package indexes on the first run.

- **What is the current behavior?**
If there is a problem downloading a package index the `core update-index` command will stop and not complete the update of the remaining custom indexes url.

* **What is the new behavior?**
The `core update-index` command will always complete the update of all indexes.

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**
Yes

* **Other information**:
Fix #1788

### CODE REVIEW

File: cli/update/update.go [hunk 1]
```diff
@@ -56,9 +56,9 @@ func runUpdateCommand(cmd *cobra.Command, args []string) {
 	inst := instance.CreateInstanceAndRunFirstUpdate()
 	logrus.Info("Executing `arduino-cli update`")
 
-	err := commands.UpdateCoreLibrariesIndex(context.Background(), &rpc.UpdateCoreLibrariesIndexRequest{
-		Instance: inst,
-	}, output.ProgressBar())
+	err := commands.UpdateCoreLibrariesIndex(context.Background(), &rpc.UpdateCoreLibrariesIndexRequest{Instance: inst},
+		output.ProgressBar(),
+		output.PrintErrorFromDownloadResult(tr("Error updating index")))
```
Comment (per1234) [inline cli/update/update.go:61]: I think there is a problem with the progress bar:

```text
$ arduino-cli core update-index --additional-urls http://example.com/package_foo_index.json
Downloading index: package_index.tar.bz2 downloaded
 0 / ? [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------=]   0.00%Error updating index: Error downloading index 'http://example.com/package_foo_index.json': Server responded with: 404 Not Found
```

Note that that "Error updating index" was tacked on at the end of the progress bar.

I see that the progress bar disappears for the index download processes that are successful.

**Review by per1234 — CHANGES_REQUESTED** [review]

File: cli/output/rpc_progress.go [hunk 2]
```diff
@@ -40,6 +41,21 @@ func ProgressBar() rpc.DownloadProgressCB {
 	}
 }
 
+// PrintErrorFromDownloadResult returns a DownloadResultCB that only prints
+// the errors with the give message prefixed.
+func PrintErrorFromDownloadResult(msg string) rpc.DownloadResultCB {
+	if OutputFormat != "json" {
```
Comment (per1234) [inline cli/output/rpc_progress.go:47]: The `json` output format should not be given special treatment. All the machine readable output formats (`json`, `jsonmini`, `yaml`) must be given equal consideration in this type of code. 

There should be a single centralized function to handle this sort of thing instead of unmaintained "magic strings" scattered throughout the codebase.

**Review by per1234 — CHANGES_REQUESTED** [review]
### Describe the problem

The value of the `cc.arduino.cli.commands.v1.ArduinoCoreService.DownloadResult.successful` field is set to `true` when a download fails.

### To reproduce

#### Set up

```text
$ arduino-cli version
arduino-cli.exe  Version: git-snapshot Commit: 732bdc54 Date: 2022-09-07T09:59:11Z

$ export ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS=http://example.com/package_foo_index.json

$ arduino-cli daemon
Daemon is now listening on 127.0.0.1:50051
```

#### Demo

Use [grpcurl](https://github.com/fullstorydev/grpcurl) to run the following commands in another terminal.

```text
$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Create

{
  "instance": {
    "id": 1
  }
}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.Init

{
  "error": {
    "code": 9,
    "message": "Loading index file: loading json index file C:\\Users\\per\\AppData\\Local\\Arduino15\\package_foo_index.json: open C:\\Users\\per\\AppData\\Local\\Arduino15\\package_foo_index.json: The system cannot find the file specified."
  }
}

$ grpcurl \
  -plaintext \
  -import-path ./rpc \
  -proto cc/arduino/cli/commands/v1/commands.proto \
  -d '{"instance": {"id": 1}}' \
  127.0.0.1:50051 \
  cc.arduino.cli.commands.v1.ArduinoCoreService.UpdateIndex

{
  "downloadProgress": {
    "url": "https://downloads.arduino.cc/packages/package_index.tar.bz2",
    "file": "Downloading index: package_index.tar.bz2",
    "totalSize": "43541"
  }
}
{
  "downloadProgress": {
    "downloaded": "43541"
  }
}
{
  "downloadProgress": {
    "completed": true
  }
}
{
  "downloadResult": {
    "url": "https://downloads.arduino.cc/packages/package_index.tar.bz2",
    "successful": true
  }
}
{
  "downloadProgress": {
    "url": "http://example.com/package_foo_index.json",
    "file": "Downloading index: package_foo_index.json",
    "totalSize": "-1"
  }
}
{
  "downloadProgress": {
    "downloaded": "1256"
  }
}
{
  "downloadResult": {
    "url": "http://example.com/package_foo_index.json",
    "error": "Error downloading index 'http://example.com/package_foo_index.json': Server responded with: 404 Not Found"
  }
}
{
  "downloadResult": {
    "url": "http://example.com/package_foo_index.json",
    "successful": true
  }
}
ERROR:
  Code: Internal
  Message: Some indexes could not be updated.
```

🐛 The value of the `cc.arduino.cli.commands.v1.ArduinoCoreService.DownloadResult.successful` field was `true` for the failed download of `http://example.com/package_foo_index.json`.

### Expected behavior

The value of the `cc.arduino.cli.commands.v1.ArduinoCoreService.DownloadResult.successful` field is set to `false` when the download fails.

File: cli/update/update.go (hunk 1 above)
Comment (cmaglie) [reply cli/update/update.go:61]: great catch!

File: cli/output/rpc_progress.go (hunk 2 above)
Comment (cmaglie) [reply cli/output/rpc_progress.go:47]: You're right, but this is outside the scope of this specific PR, I'll open a new issue for this one.

**Comment by cmaglie** [comment]
> :bug: The value of the cc.arduino.cli.commands.v1.ArduinoCoreService.DownloadResult.successful field was true for the failed download of http://example.com/package_foo_index.json.

I've pushed the fix for this problem, and the other one https://github.com/arduino/arduino-cli/pull/1866#discussion_r964583424

**Review by per1234 — APPROVED** [review]
The bugs reported in my previous review have been resolved and it is working as expected now.

Thanks Cristian!

**Review by umbynos — APPROVED** [review]
